// From https://geschicktgendern.de/ under CC-BY-NC-SA
// https://creativecommons.org/licenses/by-nc-sa/4.0/deed.de

export const wordList = [
  ["Abbrecherquote", "Abbruchquote"],
  [
    "Abenteurer",
    "Waghals; abenteuerliebende Person; abenteuerlustige Person; abenteuermutige Person; Abenteuermensch",
  ],
  ["Abiturient", "Abitur ablegende Person; Person, die Abitur macht"],
  ["Abnehmer", "Abnehmende"],
  [
    "Abonnent",
    "Bezugsperson; medienbeziehende Person; ein Abonnement beziehende Person",
  ],
  ["Abonnenten", "Abonnement-Beziehende; Abonnierende"],
  ["Absender", "abgesandt durch ...; absendende Person"],
  ["Absolventen", "Alumni ; Abschluss inhabende Person; Person mit Abschluss"],
  ["Absolventenpraktikum", "Praktikum (direkt) nach Studienabschluss"],
  ["Abteilungsleiter", "Abteilungsleitung"],
  ["Abteilungsleiter", "Abteilungsleitungen; Abteilungsleitende"],
  [
    "Abteilungsleitertreffen",
    "Treffen der Abteilungsleitungen; Treffen der Leitungsebene",
  ],
  ["Administrator", "Administration; Admin"],
  ["Administratoren", "Administration; Admins; Administrierende"],
  ["Adressat", "adressierte Person; an ..."],
  ["Agent", "auskundschaftende Person; spionierende Person"],
  ["Agent", "jemanden/etwas vermittelnde Person"],
  ["Agententhriller", "Spionagethriller"],
  [
    "Ahnen",
    "[dieser Begriff ist im Plural bereits genderneutral: sg. die Ahne (f.) oder der Ahne (m.) -> pl. die Ahnen (f.) und die Ahnen (m.)]",
  ],
  ["Akademiker", "Studierte; Personen mit Hochschulabschluss"],
  ["Akteure", "Beteiligte; Agierende; Handelnde; Aktive"],
  ["Akteursnetzwerk", "Netzwerk von Engagierten; Netzwerk von Aktiven"],
  ["Aktionär", "Person mit Aktienbesitz"],
  ["Aktionäre", "Aktien-/Anteilshabende"],
  ["Aktionärsversammlung", "Versammlung von Personen mit Aktienbesitz"],
  ["Aktivist", "engagierte Person; politisch aktiver Mensch"],
  [
    "Aktivisten",
    "engagierte Personen; politisch aktive Menschen; zielstrebig Handelnde",
  ],
  ["Alkoholiker", "alkoholsüchtige Person; Person mit Alkoholsucht"],
  ["Alkoholiker", "Alkoholsüchtige; Menschen mit Alkoholsucht"],
  [
    "Alleinerziehende",
    "Ein-Eltern-Haushalt; Ein-Eltern-Familie; alleinerziehende Person",
  ],
  ["Alleinerziehende", "[im Plural ist dieses Wort schon gendergerecht]"],
  [
    "Allergiker",
    "Menschen mit Allergie; Allergiegeplagte; allergieleidende Personen",
  ],
  ["Allgemeinmediziner", "Allgemeinmedizin praktizierende Person"],
  ["Alltagshelfer", "Alltagshilfe"],
  ["Älpler", "Alpwirtschaft Betreibende"],
  [
    "Altenpfleger",
    "Pflegefachkraft; Pflegefachperson; Altenpflegeperson; Krankenpflegeperson; Fachkraft für Altenpflege",
  ],
  [
    "Altersgenossen",
    "gleich Alte; Menschen derselben Altersgruppe; Gleichaltrige",
  ],
  ["Alumni", "Ehemalige"],
  ["Amateur", "Neuling; Person ohne Vorkenntnisse"],
  ["Amateure", "Anfangende; Beginnende"],
  [
    "Ampelmännchen",
    "Ampelfiguren; Ampelfigürchen; Ampelmenschlein (s. auch Blog (klick))",
  ],
  [
    "Amtsinhaber",
    "Amt innehabende Person; eine mit einem Amt betraute Person; amtierende Person im Bereich XY/ in Position XY; amtsverantwortliche Person für den Bereich XY",
  ],
  ["Analytiker", "Analysierende"],
  [
    "Anbieter",
    "Angebot (von ...); Herstellung; angebotsstellende Person; angebotsmachende Person",
  ],
  ["andere", "Gegenüber"],
  [
    "Anfänger",
    "Unerfahrene; Menschen ohne Vorkenntnisse; Menschen ohne Vorerfahrung; Beginnende; Neulinge",
  ],
  [
    "Anfängerkurs",
    "Einstiegskurs; Grundkurs; Kurs für Menschen ohne Vorkenntnisse; Kurs für Menschen ohne Vorerfahrung",
  ],
  ["Anforderer", "anfordernde Person/Abteilung"],
  ["Angehöriger", "Familienmitglied; Mitglied von ..."],
  ["Angeklagter", "angeklagte Person"],
  [
    "Angesprochener",
    "angesprochene Person; kontaktierte Person; lyrisches Du [Kontext Lyrikanalyse]",
  ],
  ["Angreifer", "angreifende Person"],
  ["Angreifer", "Angreifende"],
  [
    "Anhänger",
    "Fans; Begeisterte; Gleichgesinnte; Unterstützende; Sympathisierende; sich (einer Bewegung, einem Verein) Zuordnende; Zugehörige (einer Bewegung); Mitwirkende; Befürwortende",
  ],
  ["Anhängerschaft", "Gefolgschaft"],
  ["Animateur", "Freizeitbetreuungsperson"],
  ["Sprachanimateur", "zum Sprechen animierende/anregende Person"],
  ["Animateure", "Animierende"],
  ["Sprachanimateure", "... Sprachanimierende"],
  ["Stimmungsanimateure", "... Stimmungsunterhaltende"],
  ["Anleger", "Anlegende"],
  ["Anleiter", "anleitende Person; Anleitung"],
  ["Anlieger", "anwohnende Person"],
  ["Anlieger", "Anliegende; anwohnende Personen; Anwohnende"],
  ["Anordner", "Anordnung, anordnende Person"],
  [
    "Anrainer",
    "Person nebenan; Person, die nebenan wohnt; Person, der das Grundstück nebenan gehört",
  ],
  ["Anrufer", "Anrufende"],
  [
    "Ansprechpartner",
    "Ansprechperson; Kontakt; Kontaktperson; Auskunft gibt ... ; zuständig ist ...",
  ],
  ["Antagonist", "widerstreitende Person; Counterpart; Konkurrenz"],
  ["Anteilseigner", "Anteilsinhabende"],
  [
    "Antragsteller",
    "beantragende Person/Einrichtung; die Person, die einen Antrag stellt; die antragstellende Person; Antrag gestellt von ...",
  ],
  [
    "Anwalt",
    "Rechtsvertretung; gesetzliche Vertretung in Rechtsangelegenheiten; Rechtsbeistand (nicht empfohlen)  ; Mitglied der Anwaltschaft",
  ],
  ["Anwaltskosten", "Kosten für die Rechtsvertretung"],
  ["Anwärter", "Person im Vorbereitungsdienst"],
  ["Anwender", "Nutzende; Anwendende; Personen, die ... anwenden; Anwendung"],
  ["anwenderbezogen", "anwendungsbezogen; praxisbezogen"],
  ["Anwohner", "alle, die in dieser Straße wohnen; Anwohnende; Nachbarschaft"],
  [
    "Apotheker",
    "(approbierte) Arzneikundige; approbierte pharmazeutische Fachkräfte",
  ],
  ["Arbeiter", "Arbeitskraft"],
  ["Arbeiter", "Erwerbstätige; Belegschaft; Beschäftigte; Arbeitskräfte"],
  ["Arbeiterklasse", "arbeitende Klasse"],
  [
    "Arbeitgeber",
    "Führungskraft; arbeitgebendes Unternehmen; Person, die Arbeitsplätze zur Verfügung stellt; [im Arbeitsvertrag konkret:] Firma, Unternehmen, Gesellschaft, Genossenschaft, Einrichtung, Institution, Amt, Behörde, ...",
  ],
  ["Arbeitgeber", "Arbeitgebende; Betriebe; Unternehmen"],
  ["Arbeitgeberattraktivität", "Arbeitsplatzattraktivität"],
  ["Arbeitgebermarke", "Unternehmensmarke; Employer Branding"],
  ["Arbeitgebermarketing", "Marketing für Arbeitgebende"],
  [
    "Arbeitgebervorteile",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Arbeitnehmer", "angestellte Person; beschäftigte Person"],
  ["Arbeitnehmer", "Beschäftigte; Arbeitskräfte; Belegschaft; Personal"],
  [
    "Arbeitnehmervertreter",
    "Arbeitnehmendenvertretung; Betriebsrat; Personalrat; Beschäftigtenvertretung",
  ],
  ["Arbeitskollegen", "Teammitglieder"],
  ["Archäologen", "in der Archäologie tätige Person"],
  ["Architekten", "Architekturschaffende"],
  ["Archivar", "Fachkraft für Archivwesen"],
  ["Archivare", "Archivierende"],
  ["Arzt", "Person im ärztlichen Dienst; ärztliches Fachpersonal"],
  ["Ärzte", "ärztliches (Fach-)Personal; (ggf. Ärzteschaft)"],
  [
    "Arztbesuch",
    "ärztlicher Kontakt; ärztliche Sprechstunde; Besuch der ärztlichen Sprechstunde; ärztliche Visite",
  ],
  [
    "Arztbrief",
    "Entlassungsbrief; Entlassbericht; ärztlicher/medizinischer (Abschluss-)Bericht; ärztliche Epikrise; ärztlicher Brief; (ärztlicher) Befundbericht; ärztliches Informationsschreiben; ärztliche Information",
  ],
  ["Arztgeheimnis", "ärztliche Schweigepflicht"],
  [
    "Arzthelferinnen",
    "Medizinische Fachangestellte; medizinsche Fachangestellte",
  ],
  [
    "Arztkosten",
    "(ärztliche) Behandlungskosten; Kosten für medizinische Leistungen",
  ],
  [
    "Arzt-Patienten-Kommunikation",
    "Kommunikation zwischen behandelnder und behandelter Person",
  ],
  [
    "Arzt-Patienten-Verhältnis",
    "ärztliches Vertrauensverhältnis; medizinisches Behandlungsverhältnis",
  ],
  [
    "Arztpraxis",
    "Praxis für ...-medizin (z.B. Praxis für Allgemeinmedizin); ärztliche Praxis",
  ],
  ["Arzttermin", "Behandlungstermin; Vorsorgetermin"],
  ["Arztwahl", "Wahl des ärztlichen Fachpersonals"],
  [
    "Aspirant",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Assessor",
    "sachverständige Person; taxierende Person; einschätzende Person; schadensachverständige Person",
  ],
  [
    "Assessoren",
    "Sachverständige; Taxierende; Einschätzende; Schadensachverständige",
  ],
  ["Assistent", "Assistenz"],
  [
    "Assistenzarzt",
    "Person in fachärztlicher Weiterbildung; ärztliches Fachpersonal in Weiterbildung",
  ],
  ["Astronaut", "ins Weltall reisende Person"],
  ["Astronauten", "Weltraumreisende"],
  ["Asylbewerber", "Asylsuchende; Personen im Asylverfahren"],
  [
    "Atheist",
    "atheistische Person; religionsfreie Person; nichtgläubige Person; irreligiöse Person; glaubenslose Person; areligiöse Person",
  ],
  ["Athlet", "sporttreibende Person"],
  ["Athleten", "Sporttreibende; Wettkämpfende"],
  ["Attentäter", "Person, die ein Attentat verübt"],
  ["Auditor", "auditdurchführende Person"],
  [
    "Auftraggeber",
    "Auftraggebende; auftraggebende Personen; in Auftrag gegeben von ...",
  ],
  ["Auftragnehmer", "einen Auftrag entgegennehmende / annehmende Person"],
  ["Auftragnehmer", "Auftragnehmende"],
  ["Augenoptiker", "Optikfachgeschäft"],
  ["Ausbilder", "ausbildender Betrieb; Lehrkraft"],
  ["Ausbilder", "Ausbildende "],
  ["Ausbildungsbewerber", "eine Ausbildung suchende Person"],
  [
    "Ausländer",
    "Person aus dem Ausland; Person nichtdeutscher Herkunft; ausländische Person; Person mit anderer Staatsangehörigkeit",
  ],
  ["Ausländerbehörde", "Migrationsamt/-stelle; Zuwanderungsamt/-stelle"],
  ["Aussiedler", "ausgesiedelte Person"],
  ["Aussiedler", "ausgesiedelte Personen"],
  ["Aussteiger", "[aus einer Szene] aussteigende Person"],
  ["Aussteller", "ausstellende Person; ausstellende Institution"],
  ["Aussteller", "Präsentierende; Ausstellende"],
  [
    "Ausstellerausweis",
    "Ausweis der Ausstellenden; Ausweis der ausstellenden Person",
  ],
  ["Ausstellerliste", "Liste der Ausstellenden; Ausstellendenliste"],
  ["Auswanderer", "auswandernde Person; ausgewanderte Person"],
  ["Auswanderer", "Auswandernde; Ausgewanderte"],
  ["Ausweisinhaber", "Ausweis inhabende Person"],
  [
    "Auszubildender",
    "Nachwuchskraft; Person in Ausbildung; auszubildende Person; lernende Person",
  ],
  ["Auszubildende", "[im Plural ist dieses Wort schon gendergerecht]"],
  [
    "Autofahrer",
    "Auto fahrende Person; Auto führende Person; Person am Steuer",
  ],
  ["Autofahrer", "Autofahrende; Personen am Steuer"],
  ["Autor", "bücherschreibende Person"],
  [
    "Autoren",
    "Autorenschaft; Urheberrechtsinhabende; Verfassende; Schreibende; Literaturschaffende; wissenschaftlich Publizierende; Auktorierende ",
  ],
  ["Babysitter", "Aufsichtsperson; babysittende Person; Kinderbetreuung"],
  ["Babysitter", "Babysittende"],
  [
    "Bäcker",
    "Backwaren produzierende Person; Gebäck herstellende Person; Bäckerei",
  ],
  ["Bäcker", "Backende; im Backgewerbe Tätige; professionell Backende"],
  ["Bademeister", "Badeaufsicht"],
  ["Bankräuber", "Bankausraubende"],
  ["Barkeeper", "Bar-Servicekraft; Servicekraft (an) der Bar"],
  ["Bauarbeiter", "Bauarbeiten ausführendes (Fach-)Personal"],
  [
    "Bauern",
    "Landwirtschaft Betreibende; landwirtschaftlich Beschäftigte; Beschäftigte in der Landwirtschaft; bäuerliche Bevölkerung [historischer Kontext]",
  ],
  ["Bauernkrieg", "Krieg der landbewirtschaftenden Bevölkerung"],
  ["Bauherr", "den Bau in Auftrag gebende Person"],
  [
    "Bauherren",
    "Bauverantwortliche; Bauleute; den Bau in Auftrag gebende Personen",
  ],
  [
    "Bauherrschaft",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Bauingenieur",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Baumpfleger", "Baumpflege"],
  [
    "Bauträger",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Beamter", "verbeamtete Person; Person im Beamtenstatus; der/die Beamte "],
  ["Beamte", "Bedienstete"],
  [
    "Beamtenlaufbahn",
    "verbeamteter Werdegang; Laufbahn im öffentlichen Dienst mit Aussicht auf Verbeamtung",
  ],
  ["Bearbeiter", "den Vorgang betreuende Person; zuständige Person"],
  ["Beauftragter", "beauftragte Person"],
  ["Bediener", "bedienende Person"],
  ["Bediensteter", "bedienstete Person"],
  ["Befrager", "befragende Person; Person, die befragt (hat)"],
  ["Befragter", "befragte Person; Person, die befragt wurde"],
  ["Befürworter", "befürwortende Person; zustimmende Person; Zustimmung"],
  ["Befürworter", "Unterstützung; Zustimmende; Mitwirkende; Befürwortende"],
  ["Behinderter", "Mensch mit Behinderung; Mensch mit Beeinträchtigung"],
  ["Beisitzer", "Beisitzende"],
  [
    "Bekannter",
    "Person aus dem Bekanntenkreis; (mir) bekannte Person; Bekanntschaft",
  ],
  ["bemannt", "besetzt; mit Personen besetzt; astronautisch"],
  ["bemuttern", "fürsorglich sein, verhätscheln, umsorgen"],
  ["Benutzer", "Anwendende; Nutzende; Personen(-gruppen)"],
  [
    "benutzerdefiniert",
    "maßgeschneidert; speziell; passgenau; individuell einstellbar; spezifisch",
  ],
  [
    "benutzerfreundlich",
    "praktisch / leicht zu bedienen; bedienungsfreundlich; benutzungsfreundlich",
  ],
  [
    "Benutzerfreundlichkeit",
    "Nutzungsfreundlichkeit; Benutzungsfreundlichkeit",
  ],
  [
    "Benutzerfunktion",
    "zielgruppengerechte Funktion; nutzenorientierte Funktion",
  ],
  ["Benutzerkonto", "Account; Konto; Zugang; Profil"],
  ["Benutzername", "Anmeldename; Nickname; Pseudonym"],
  ["Benutzeroberfläche", "Bedienoberfläche; Benutzungsoberfläche"],
  ["Benutzerordnung", "(Be-)Nutzungsordnung"],
  ["Benutzerportal", "Benutzungsportal"],
  [
    "Benutzerschnittstelle",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Benutzerverwaltung", "Kontoverwaltung; Zugangsverwaltung"],
  ["Beobachter", "Beobachtende"],
  [
    "Berater",
    "beratende Person; die Beratung erfolgt durch ... ; Sie werden beraten von ...",
  ],
  ["Beratertätigkeit", "beratende Tätigkeit; Beratung"],
  ["Beraterverzeichnis", "Verzeichnis beratender Personen"],
  ["bergmännisch", "im Bergbau tätig"],
  ["Bergsteiger", "Bergbegeisterte"],
  ["Berichterstatter", "Bericht erstattende Person"],
  ["Berichterstatter", "Berichtende"],
  ["Berliner", "die Berliner Bevölkerung"],
  ["Berufsanfänger", "Berufsunerfahrene; Berufseinsteigende"],
  ["Berufskraftfahrer", "qualifizierte fahrzeugführende Person (nach BKrFQG)"],
  ["Berufskraftfahrer", "Berufskraftfahrende "],
  [
    "Berufsschüler",
    "Auszubildende; Beruflernende; eine Berufsschule Besuchende; an einer Berufsschule Lernende",
  ],
  [
    "Beschäftigter",
    "Arbeitskraft; beschäftigte Person; angestellte Person; Person im Beschäftigungsverhältnis",
  ],
  ["Beschuldigter", "beschuldigte Person"],
  ["Beschwerdeführer", "Beschwerdeführende"],
  ["Besitzer", "besitzhabende Person"],
  ["Besteller", "bestellende Person; Kundschaft"],
  ["Besucher", "Gäste ; Publikum; Besuche; Besuchende"],
  ["Besucheranschrift", "Besuchsanschrift"],
  ["Besuchergruppe", "Besuchsgruppe"],
  ["Besuchermagnet", "Publikumsmagnet; Besuchsmagnet; Tourismusmagnet"],
  ["Besucherparkplatz", "Besuchsparkplatz"],
  [
    "Besucherrückgang",
    "sinkende Nachfrage; Rückgang der Besuche;  wurde weniger frequentiert als im Jahr zuvor ",
  ],
  [
    "Besucherzahl",
    "Besuchszahl; Frequentierung; Klickzahl; Interesse; Inanspruchnahme; Gästezahlen",
  ],
  ["Betrachter", "Betrachtende"],
  ["Betreiber", "Betriebsgesellschaft; betreibende Firma; Betrieb"],
  ["Betreuer", "Betreuungsperson"],
  ["Betreuer", "Betreuungspersonal"],
  ["Betriebsrat", "Mitglied des Betriebsrates "],
  [
    "Betriebsräte",
    "Mitglieder des Betriebsrates; der Betriebsrat; Mitarbeitendenvertretung; der Personalrat ",
  ],
  ["Betroffener", "betroffene Person; Opfer"],
  ["Betrüger", "unehrliche Person"],
  ["Bewahrer", "bewahrende Person"],
  ["Bewerber", "sich bewerbende Person"],
  ["Bewerber", "Bewerbende; sich bewerbende Personen"],
  ["Bewerberzahlen", "Bewerbungszahlen"],
  [
    "Bewohner",
    "in ... Lebende; in ... lebende Menschen; Ortsansässige; Bewohnende; Bewohnerschaft",
  ],
  ["Bewohnerzimmer", "Bewohnendenzimmer; Zimmer"],
  ["Bieter", "bietende Partei; bietende Person"],
  ["Bildungsträger", "Bildungstragende"],
  ["Biografieträger", "Biografietragende"],
  [
    "Blindenführer",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Blockwart", "Gebietsaufsicht; Blockaufsicht"],
  ["Blogger", "bloggende Personen; Personen, die einen Blog schreiben"],
  ["Bogenschütze", "Bogenschießende Person"],
  ["Bote", "Botschaft überbringende Person"],
  ["Brandschutzbeauftragter", "beauftragte Person für Brandschutz"],
  ["Brautpaar", "Hochzeitspaar; verlobtes Paar"],
  ["Botschafter", "Spitze des Diplomatischen Corps; Repräsentanz"],
  ["Briefträger", "Briefzustellung; Postzustellung"],
  ["Brüderlichkeit", "Mitmenschlichkeit; Solidarität; Geschwisterlichkeit"],
  ["Buhmann", "Sündenbock; Feindbild"],
  ["Buddhisten", "Menschen buddhistischen Glaubens"],
  ["Bundespräsidentenwahl", "Bundespräsidentschaftswahl; BP-Wahl"],
  ["Bundestagspräsident", "Bundestagsvorsitz"],
  [
    "Bürger",
    "Mitglied des Staates / der Stadt; dem Staat zugehörige Person; Mitmensch; rat-/hilfe-/unterstützungssuchende Person [im Verwaltungskontext]; Individuum; Einzelperson; einzelner Mensch innerhalb der Bevölkerung; bürgerliche Person [historischer Kontext]",
  ],
  [
    "Bürger",
    "Bevölkerung; Einwohnerschaft; (Kommunal-)Wahlberechtigte; Staatsangehörige; Einheimische; im Ort/in der Stadt ... Wohnende; Stimmberechtigte; allgemeine Öffentlichkeit; breites Publikum; bürgerliche Bevölkerung; Bürgerschaft; Bürgertum",
  ],
  ["Bürgeramt", "Amt; Gemeindeamt; Verwaltung"],
  ["Bürgerbeteiligung", "Direkte Demokratie; Beteiligung der Bevölkerung"],
  [
    "Bürgerhaus",
    "Gemeindehaus; Stadthaus; Kulturzentrum; Stadtteilzentrum; selbstverwaltetes Zentrum",
  ],
  ["Bürgerkrieg", "Volkskrieg"],
  ["Bürgermeister", "Stadtoberhaupt"],
  ["Bürgermeisterkandidat", "Kandidatur für das Amt des Stadtoberhaupts"],
  [
    "bürgernah",
    "serviceorientiert; bedürfnisorientiert; publikumsorientiert; menschenorientiert; im Kontakt",
  ],
  ["Bürgernähe", "Volksnähe; Bevölkerungsnähe"],
  [
    "Bürgerrat",
    "Volksrat; Menschenrat; weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Bürgerrechte", "Rechte des deutschen (oder anderer Staaten) Staatsvolkes"],
  ["Bürgersteig", "Gehweg; Fußweg"],
  ["Bürgervertretung", "Vertretung der Öffentlichkeit"],
  [
    "Bürgerzentrum",
    "Kulturzentrum; Stadtteilzentrum; selbstverwaltetes Zentrum",
  ],
  ["Bürokrat", "bürokratische Person; bürokratisch veranlagte Person"],
  ["Busfahrer", "Busführung; busführende Person"],
  [
    "Callcenteroperator",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Camper", "campende Person; zeltende Person; Zeltplatzmensch"],
  [
    "Chef",
    "vorgesetzte Person; Leitungsperson; Leitung; Kopf (eines Unternehmens / einer Abteilung)",
  ],
  ["Chefs", "Vorgesetzte; Leitung"],
  ["Chefarzt", "Ärztliche Leitung; Ärztliche Klinikleitung\n\n"],
  ["Chefarztbehandlung", "chefärztliche Behandlung"],
  [
    "Chefsache",
    "Sache mit oberster Priorität; Angelegenheit mit besonderer Wichtigkeit; dringliche Sache",
  ],
  ["Chemiker", "Fachkraft für Chemie"],
  [
    "Chirurg",
    "chirurgische Fachkraft; chirurgische Fachperson; ärztliche Fachkraft der ...-Chirurgie",
  ],
  ["Chirurgen", "chirurgisches Fachpersonal"],
  ["Chirurgenstahl", "Chirurgiestahl"],
  ["Christen", "Menschen christlichen Glaubens"],
  ["Chorleiter", "Chorleitung"],
  ["Chorleiter", "Chorleitende; Chorleitungen"],
  ["Coach", "Begleitung; Beratung; coachende Person"],
  ["Damenprogramm", "Begleitprogramm"],
  ["Darsteller", "darstellende Person"],
  [
    "Kinderdarsteller",
    "... darstellende Person im Kindesalter; ... schauspielendes/darstellendes Kind",
  ],
  ["Darsteller", "Rollen; Besetzung; Darstellende"],
  ["Kinderdarsteller", "... Darstellende kindlichen Alters"],
  [
    "Datenschutzbeauftragter",
    "Fachperson für Datenschutz; Datenschutzverantwortlichkeit",
  ],
  ["Dekan", "Leitung des Dekanats; Dekanat"],
  ["Delegierter", "delegierte Person"],
  ["Demonstranten", "Demonstrierende"],
  ["Designer", "Designschaffende"],
  [
    "Deutscher",
    "Person aus Deutschland; deutsche Person; Person mit deutscher Staatsangehörigkeit",
  ],
  [
    "Dezernent",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Dichter", "dichtende Person; poetische Person"],
  ["Dieb", "Eigentum entwendende Person"],
  ["Dienstherr", "Dienstaufsichtsperson; Dienstbehörde"],
  [
    "Dienstherrengenehmigung",
    "Vorgesetztengenehmigung ; Genehmigung der vorgesetzten Führungskraft; Dienststellengenehmigung; behördliche Genehmigung",
  ],
  [
    "Dienstleister",
    "dienstleistende Person; dienstleistendes Unternehmen; Dienstleitungsunternehmen",
  ],
  ["Diplomingenieur", "diplomierte technische Fachkraft"],
  ["Direktor", "Leitung [z.B. Schulleitung; Institutsleitung; Museumsleitung]"],
  ["Dirigent", "unter dem Dirigat von ...; unter Leitung von ..."],
  [
    "Dispatcher",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Disponent", "Disposition"],
  ["DJ", "der/die DJ"],
  ["Doktoranden", "Promovierende"],
  ["Doktorandenkolleg", "Promotionskolleg; Promovierendenkolleg"],
  ["Doktorarbeit", "Promotion"],
  [
    "Doktorvater/-mutter",
    "Promotionsbetreuung; Vorsitz des Promotionskomitees",
  ],
  ["Dokumenteninhaber", "im Besitz von Dokumenten"],
  ["Dolmetscher", "(simultan / konsekutiv) dolmetschende Fachkraft"],
  [
    "Dönermann",
    "Dönerimbiss; Dönerverkauf; Kebapverkauf; Dönerfachgeschäft; Dönerbude",
  ],
  ["Doppelgänger", "Double; Ebenbild; Doppelperson"],
  [
    "Dozent",
    "lehrende Person; Lehrkraft; Lehrperson; vortragende Person; Seminarleitung",
  ],
  ["Dozenten", "Dozierende; Lehrpersonal; Lehrende"],
  ["Dozententätigkeit", "Lehrtätigkeit"],
  ["Drachenlord", "herrschende Drachenperson"],
  ["Dritter", "dritte Person"],
  ["Editor", "herausgebende Person"],
  ["Ehegatten", "Eheleute"],
  ["Ehepartner", "geehelichte Person"],
  ["Ehrenamtler", "Ehrenamtliche; Freiwillige; (ehrenamtlich) Engagierte"],
  ["Ehrenmann", "Ehrenperson"],
  ["Eigentümer", "(im) Eigentum von ..."],
  ["Eigner", "s. Eigentümer"],
  ["Einbrecher", "einbrechende Personen"],
  ["Ein-Mann-Betrieb", "Ein-Personen-Betrieb"],
  ["Einsteigerkurs", "Einstiegskurs; Grundlagenkurs; Grundkurs; Basiskurs"],
  [
    "Einwanderer",
    "Menschen mit Migrationshintergrund /-geschichte /-biografie; Menschen mit internationaler Geschichte",
  ],
  [
    "Einwohner",
    "die Menschen der Stadt XY; Population; Bevölkerung; gemeldete Personen",
  ],
  ["Einwohnerdichte", "Bevölkerungsdichte"],
  ["Einwohnerzahl", "Bevölkerungszahl"],
  [
    "Einzelhändler",
    "Person des Einzelhandels; Betrieb im Einzelhandel; im Einzelhandel tätige Person",
  ],
  ["Einzelkämpfer", "Einzelkämpfende; Kriegsteilnehmende"],
  ["Einzelne", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Einziger", "einzige Person"],
  ["Elektriker", "Fachkraft für Elektrotechnik"],
  ["Elektroniker", "Elektrofachkraft"],
  ["Elektrotechniker", "Fachkraft für elektrotechnische Anlagen"],
  [
    "Empfänger",
    "empfangsberechtigte Person; empfangen von ... ; für ... ; bestimmt für ...",
  ],
  ["Empfangsdame", "Empfang; Person/Perosonal am Empfang; Rezeption"],
  [
    "Endverbraucher",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Energieversorger", "Energieversorgungsunternehmen"],
  ["Enkel", "Enkelkind; Kindeskind"],
  ["Entdecker", "entdeckt von ..."],
  [
    "Entdecker",
    "entdeckt von ... ; entdeckende Personen /Kinder; Forschende; Entdeckende",
  ],
  ["Enthusiast", "enthusiastische Person; begeistere Person"],
  ["Enthusiasten", "Begeistere"],
  ["Entscheider", "Entscheidung fällende Person; entscheidungsbefugte Person"],
  ["Entscheidungsträger", "Person mit Entscheidungsbefugnis"],
  ["Entscheidungsträger", "Entscheidungtragende"],
  ["Entwickler", "Entwickelnde; Erfindende"],
  ["Erbauer", "Konstruierende; Erschaffende; erbaut von ...; ein Bau von ..."],
  ["Erbe", "erbberechtigte Person"],
  ["Erben", "Erbberechtigte"],
  ["Erfinder", "erfindende Person"],
  ["Ergotherapeut", "in der Ergotherapie tätige Person"],
  ["Ermittler", "Ermittelnde; Ermittlungsteam"],
  ["Errichter", "errichtet von ..."],
  ["Ersteller", "erstellt von ..."],
  [
    "Ersthelfer",
    "erste Hilfe leistende Person; in Erster Hilfe geschulte Person",
  ],
  ["Ersthelfer", "Ersthelfende"],
  ["Erstsemester", "Studierende im ersten Semester; Ersti"],
  ["Erzähler", "erzählende Figur; erzählende Person; Erzählinstanz"],
  ["Erzähler", "Erzählende"],
  ["Erzeuger", "ein Produkt erzeugende Person"],
  ["Erzieher", "pädagogische Fachkraft; Erziehungskraft"],
  ["Erziehungsberechtigter", "erziehungsberechtigte Person"],
  ["EU-Kommissar", "EU-Kommissionsmitglied"],
  [
    "Exot",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Experte", "Fachgröße; Autorität; Koryphäe; Person vom Fach; Genie"],
  ["Experten", "Fachkräfte; Fachleute; Fachkundige; Sachverständige"],
  ["Expertengruppe", "Fachgruppe"],
  ["Experteninterview", "Expertiseinterview; Interview mit Fachleuten"],
  ["Expertenkommission", "Fachkommission; Kommission von Fachleuten"],
  ["Expertenrating", "Rating von Fachleuten"],
  [
    "Expertenschätzung",
    "Schätzung von Fachleuten; nach Einschätzung von Fachleuten; Expertise",
  ],
  ["Expertenstandard", "Fachstandard"],
  ["Expertentagung", "Fachtagung"],
  ["Expertentum", "Expertise"],
  ["Expertenvortrag", "Fachvortrag"],
  ["Expertenwissen", "Fachwissen; Expertise"],
  ["Extremist", "radikalisierte Person"],
  ["Facharzt", "(fach-)ärztliche Fachkraft; Fachpraxis"],
  ["Fachmann", "Fachkraft"],
  ["fachmännisch", "fachkundig"],
  [
    "Fachvermögensträger",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Fachwissenschaftler", "Fachforschende"],
  ["Fahrer", "Fahrdienst"],
  ["Fahrer", "Fahrzeugführende; Fahrende"],
  ["Fahrerhaus", "Cockpit"],
  ["Fahrerkabine", "Fahrkabine; Steuerungskabine"],
  ["Fahrersitz", "Cockpitsitz; Sitz der fahrenden Person"],
  ["Fahrgast", "mitreisende Person; gegen Entgelt transportierte Person"],
  ["Fahrgäste", "Mitfahrende; Reisende"],
  ["Fahrgastraum", "Abteil; Personenbeförderungsräume"],
  ["Fahrradfahrer", "Fahrrad Fahrende; wer mit dem Fahrrad unterwegs ist ..."],
  ["Fahrschüler", "Fahrlernende"],
  ["Fahrzeugführer", "fahrzeugführende Person; Fahrzeugführung"],
  ["Fahrzeughalter", "eine ein Fahrzeug besitzende/führende Person "],
  ["Fahrzeuglenker", "Fahrzeug lenkende Person"],
  [
    "Familienbegleiter",
    "Familienbegleitung; Familien begleitende (Fach-)Kraft",
  ],
  [
    "Familienhelfer",
    "Familienhilfe; Familien unterstützende (Fach-)Kraft; die die Familie X. unterstützende Fachperson/Fachkraft; im familienunterstützenden Dienst arbeitende / angestellte Person",
  ],
  ["Fan", "in besonderem Maße begeisterte Person"],
  ["Fans", "Begeisterte"],
  ["Basketballfans", "... Basketballbegeisterte"],
  [
    "Favorit",
    "favorisierte (antretende) Person; favorisierte Option; bevorzugte Person; Liebling",
  ],
  ["Feigling", "feige Person; Angsthase"],
  ["Feind", "verfeindete Person"],
  ["Feministin", "feministische / feministisch eingestellte Person"],
  ["Fertiger", "fertigende Person"],
  ["Fetischist", "Person mit einem Fetisch"],
  [
    "Feuerwehrmänner",
    "Einsatzkräfte der Feuerwehr; Feuerwehrangehörige; Feuerwehr; Feuerwehrleute",
  ],
  ["Filmemacher", "filmschaffende Person"],
  ["Filmemacher", "Filmschaffende"],
  ["Filmstar", "Filmgröße; Filmberühmtheit"],
  ["Finalist", "am Finale teilnehmende Person"],
  ["Finalisten", "am Finale Teilnehmende"],
  ["Finanzbeauftragter", "finanzbeauftragte Person"],
  [
    "Finanzintermediäre",
    "Anbietende von Finanzintermediation; Finanzintermediierende",
  ],
  ["Fischer", "Fisch fangende Person"],
  ["Flüchtlinge", "Geflüchtete; Flüchtende; geflüchtete Menschen"],
  ["Follower", "Follis; Follows"],
  ["Förderer", "Stelle, die Fördermittel vergibt"],
  ["Förderer", "unterstützender Personenkreis"],
  [
    "Fördermittelgeber",
    "Stelle, die Fördermittel vergibt; fördermittelgebende Stelle",
  ],
  [
    "Forscher",
    "Forschende; Universitätsmitglieder; wissenschaftliches Personal der Universität; Menschen, die in der Forschung tätig sind; Forschungsteam",
  ],
  ["Forschergemeinde", "Forschungsgemeinde"],
  ["Forscherkolloquium", "Forschungskolloquium"],
  ["Forscherteam", "Forschungsteam"],
  ["Förster", "Beschäftigte in der Forstwirtschaft"],
  ["Forstwart", "Forstaufsicht"],
  ["Fortgeschrittene", "[im Plural ist dieses Wort schon gendergerecht]"],
  [
    "Fotograf",
    "fotografierende Person; (Berufs-)Fotografie betreibende Person",
  ],
  ["Fotografen", "Fotografierende; Aufnehmende"],
  ["Freiberufler", "freiberuflich arbeitende Person"],
  ["Freigeber", "freigebende Person"],
  ["Freiwilliger", "freiwillige Person"],
  [
    "Fremdsprachler",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Freund",
    "(enge) Bezugsperson; Herzensmensch; Bekanntschaft; Lieblingsmensch; bessere Hälfte",
  ],
  ["Freunde", "Bekannte; Bezugspersonen"],
  ["Freundeskreis", "Personen in befreundeten Kreisen"],
  ["Friseur", "frisierende Person; Frisiersalon"],
  ["Friseure", "Frisierende"],
  ["Führerschein", "Fahrerlaubnis; Fahrberechtigung"],
  [
    "Funktionär",
    "in Funktion gewählte Person; verantwortliche/beauftragte/bevollmächtigte Person",
  ],
  [
    "Funktionäre",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Funktionsträger",
    "in Funktion gewählte Person; verantwortliche/beauftragte/bevollmächtigte Person",
  ],
  [
    "Fürsprecher",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Fürsprecher",
    "Mitwirkende; Beteiligte; Befürwortende; Support; Supportende",
  ],
  ["Fußballspieler", "Fußballspielende"],
  ["Fußgänger", "Menschen zu Fuß; zu Fuß Gehende; Fußverkehr"],
  ["Fußgängerstreifen", "Zebrastreifen; Straßenpassierstreifen"],
  ["Fußgängerüberweg", "Überquerung"],
  ["Fußgängerweg", "Gehweg"],
  [
    "Fußgängerzone",
    "Flanierzone; Einkaufsstraße; verkehrsfreie Zone; verkehrsberuhigter Bereich ",
  ],
  ["Gaffer", "Schaulustige"],
  ["Gamer", "Gaming People"],
  ["Gärtner", "Gartenarbeitskraft"],
  ["Gast", "Besuch; Besuchsperson"],
  ["Gastbeitrag", "Sonderbeitrag"],
  ["Gäste", "Eingeladene; Geladene; Besuche "],
  ["Gastgeber", "Einladende"],
  ["Gasthörer", "Studierende im Gaststudium"],
  ["Gasthörerstatus", "Gaststudierendenstatus; Gasthörstatus"],
  ["Gasthörerstudium", "Gaststudium; Hospitation"],
  ["Gastronomen", "Betreibende eines Gastronomiebetriebs "],
  ["Gastwirt", "Gastronomiebetriebsleitung"],
  ["Gastwirte", "Betreibende eines Gastronomiebetriebs"],
  [
    "Gefreiter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Gegenspieler",
    "gegnerische Partei; widerstreitende Person; Counterpart; Konkurrenz",
  ],
  [
    "Gegenspieler",
    "gegnerische Partei; gegnerische Spielende; feindliche Spielende; Gegenseite; Konkurrenz",
  ],
  [
    "Gegner",
    "gegnerische Partei; widerstreitende Person; Counterpart; Konkurrenz; ablehnende Person",
  ],
  [
    "Gegner",
    "gegnerische Partei; gegnerische Spielende; feindliche Spielende; Gegenseite; Konkurrenz",
  ],
  ["Geisterfahrer", "Fahrzeug in falscher Richtung; Geisterfahrzeug"],
  ["Geldgeber", "Geldgebende; support"],
  ["Gelehrter", "gelehrte Person"],
  ["Generaldirektor", "Direktoriumsleitung"],
  [
    "Generalist",
    "Universalgenie; Multitalent; fachlich breit aufgestellter Mensch",
  ],
  [
    "Generalsekretär",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Genosse", "Mitglied der Genossenschaft"],
  [
    "Geograph",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Geologe",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Geologen", "Forschende der Geologie"],
  ["Gerätewart", "Geräteaufsicht"],
  ["Gerichtsvollzieher", "Gerichtsvollzugsperson"],
  ["Geschäftsführer", "Geschäftsführung; Geschäftsleitung"],
  ["Geschäftsmänner", "Geschäftsleute"],
  ["Geschäftspartner", "geschäftliche Verbindung; geschäftlicher Kontakt"],
  ["Gesellschafter", "Betriebsgesellschaft; Beteiligte; Gesellschaftende"],
  [
    "Gesellschafter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Gesetzgeber", "Legislative; gesetzgebende Instanz; Gesetzgebende"],
  ["Gesprächspartner", "Gegenüber"],
  ["Gesprächspartner", "Gesprächsbeteiligte; Gegenüber"],
  ["Gesprächsteilnehmer", "Gesprächsbeteiligte"],
  ["Gestalter", "Gestaltende"],
  ["Gewinner", "Erster Platz"],
  ["Gläubiger", "Geld-/Kreditgebende"],
  [
    "Götter",
    "Allwissende; Allmächtige; übernatürliche Wesen; Ewige; Gottheiten",
  ],
  ["Grafiker", "Grafikprofi"],
  [
    "Grenzgänger",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Grinsepeter", "Grinsebacke; Grinsegesicht; Grinsekuchen; Sonnenschein"],
  ["Gründer", "gründende Person"],
  ["Gründerzeit", "Gründungszeit"],
  ["Gründerzentrum", "Gründungszentrum; Innovationszentrum; Tehnologiezentrum"],
  ["Grundrechtsträger", "grundrechtsberechtigte Person "],
  ["Grundschüler", "Grundschulkind"],
  ["Gruppenleiter", "Gruppenleitende; Gruppenleitung"],
  [
    "Guide",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Guru", "spirituelles Vorbild / Idol"],
  ["Gutachter", "begutachtet von ..."],
  ["Gutachter", "Sachverständige"],
  [
    "Gymnasiast",
    "Person auf einem Gymnasium; ein Gymnasium besuchende Person; gymnasial lernende Person",
  ],
  ["Gynäkologe", "medizinisches Fachpersonal für Frauenheilkunde"],
  [
    "Hacker",
    "Personen, die fremde Digitaldaten nutzen; Hackende; umfunktionierende Personen; Cyber-Kriminelle weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Hackerangriff", "Hackingangriff; Hackangriff"],
  ["Hamburger", "die Hamburger Bevölkerung"],
  ["Handlanger", "helfende Person; rechte Hand von jemandem"],
  ["Händler", "Shops; der Handel"],
  ["Handwerker", "handwerkliches Fachpersonal; handwerkliche Fachkraft"],
  ["Handwerker", "Handwerksbetriebe; Handwerkende; Fachpersonal im Handwerk"],
  [
    "Hauptcharakter",
    "[dieses Wort ist meiner Meinung nach schon gendergerecht; wer dennoch eine Alternative bevorzugt, kann diese hier nutzen:] Hauptfigur; Hauptperson; Hauptfigur; zentrale Gestalt; Schlüsselfigur; Titelrolle",
  ],
  ["Häuptling", "Oberhaupt"],
  ["Hauptmieter", "Hauptmietpartei; Hauptmietperson; Hauptmietvertragsperson"],
  ["Hausarzt", "hausärztliche Fachkraft; Hauspraxis"],
  ["Hausdame", "Hausservice"],
  [
    "Hausfrau",
    "haushaltsführende Person; Haushalt organisierende Person; Haushaltsvorstand",
  ],
  ["Hausherr", "Familienvorstand; Hausvorstand"],
  [
    "Hausmannskost",
    "einfache Küche; gut bürgerliche Küche; traditionell zubereitete Gerichte; Alltagsessen",
  ],
  ["Hausmeister", "Gebäudemanagement"],
  ["Hauswart", "Hauswartung"],
  ["Hebammen", "Geburtshelfende"],
  [
    "Held",
    "Schlüsselperson; Hauptperson; außerordentlich erfolgreiche Person; Vorbild",
  ],
  ["Helfer", "Hilfskraft; Assistenz"],
  ["Helfer", "Helfende"],
  ["Herausgeber", "herausgegeben von ..."],
  ["Herr", "..."],
  [
    "herrenlos",
    "verlassen; nicht zuzuordnen; unbeaufsichtigt; personenlos; frei; besitzlos",
  ],
  ["Herrschaften", "Personen; Leute"],
  ["Herrscher", "Staatsoberhaupt"],
  ["Hersteller", "Herstellfirma; herstellendes Unternehmen"],
  [
    "Hexe",
    "(schwarze) Zauberkraft innehabende Person; Person mit (schwarzen) Zauberkräften; mit Zauberkräften ausgestattete Person; Person, die Zauberkraft hat",
  ],
  [
    "Hinterbliebener",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Hinterbliebene", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Hirte", "hütende Person"],
  ["Historiker", "Geschichtsforschende"],
  ["Hörer", "zuhörende Person"],
  ["Hörer", "zuhörende Personen"],
  ["Hospitant", "hospitierende Person"],
  ["Hospitanten", "Hospitierende"],
  ["Humanist", "humanistische Person"],
  ["Hundehalter", "Person, die einen Hund hält"],
  ["Ich-Erzähler", "Ich-Form; Ich-Figur; erzählendes Ich"],
  ["Illustrator", "illustrierende Person"],
  ["Illustratoren", "Illustrierende"],
  ["Imker", "Bienenzüchtende Person"],
  [
    "Immigranten",
    "Menschen mit Migrationshintergrund /-geschichte /-biografie",
  ],
  ["Immobilienbesitzer", "Immobilienbesitzende"],
  ["Immobilieneigentümer", "Personen mit Immobilienbesitz"],
  ["Immobilienkaufmann", "Immobilienfachkraft"],
  [
    "Individuum",
    "[als Neutrum ist dieses Wort schon gendergerecht: DAS Individuum]",
  ],
  ["Industriekaufmänner", "Industriekaufleute"],
  ["Industriemechaniker", "Industriemechanik ausführende Person"],
  ["Influencer", "Content gestaltende Person"],
  ["Informant", "Informationsquelle; Quelle"],
  ["Informatiker", "auf den IT-Bereich spezialisierte Person"],
  [
    "Informationssicherheitsbeauftragter",
    "beauftragte Person für Informationssicherheit",
  ],
  [
    "Ingenieur",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Ingenieurberuf", "Ingenieursberuf"],
  ["Ingenieure", "Ingenieursberuf Ausübende"],
  [
    "Ingenieurwesen",
    "Technikwissenschaften; technische Wissenschaften; Technik",
  ],
  ["Inhaber", "etwas innehabende Person"],
  ["inhabergeführt", "besitzgeführter; besitzgeleiteter"],
  ["Inhaber", "Inhabende"],
  ["Inhaftierter", "Person in Haft"],
  ["Initiatoren", "Initiierende"],
  ["Inlineskater", "Inlineskatende"],
  ["Inspekteur", "Inspektion durchführende Person"],
  ["Insasse", "inhaftierte Person"],
  ["Insasse", "mitfahrende Person"],
  ["Intendant", "Intendanz"],
  [
    "Interakteur",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Interakteure", "Interagierende"],
  ["Interessensvertreter", "Interessensvertretung"],
  ["Interessenten", "Interessierte"],
  ["Interpret", "Act"],
  ["Interviewer", "interviewende Person"],
  ["Interviewer", "Interviewende"],
  ["Interviewpartner", "Interviewte"],
  ["Investoren", "Investierende"],
  ["Jäger", "jagende Person; Person auf der Jagd"],
  ["Jäger", "Jägerschaft; jagende Personen; Personen auf der Jagd"],
  [
    "Jahrgangsbester",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["jeder", "alle; alle für sich; sämtliche"],
  ["jedermann", "alle; sämtliche"],
  [
    "Journalist",
    "Presse; Medien; jemand von der Presse/vom Fernsehen/...; wer für die Zeitung/fürs Fernsehen berichtet",
  ],
  [
    "Journalisten",
    "im Journalismus Tätige/Arbeitende; Medienschaffende; Presse; die Medien",
  ],
  ["Jubilar", "Jubiläum begehende Person; Jubiläum feiernde Person"],
  [
    "Juden",
    "Menschen jüdischen Glaubens; jüdische Menschen; Mitglieder / Angehörige der jüdischen Gemeinschaft / des jüdischen Volkes",
  ],
  ["Jugendlicher", "junge Person; junger Mensch; Teenie; Teen; Teenager"],
  [
    "Jungfrau",
    "sexuell unerfahrene Person; Person, die noch keinen Geschlechtsverkehr hatte",
  ],
  [
    "jungfräulich",
    "unangetastet; makellos; unberührt; unverändert; ursprünglich; rein; frisch; unerschlossen; unbearbeitet",
  ],
  [
    "Jurist",
    "Person mit juristischer Ausbildung; Person mit juristischem Sachverstand",
  ],
  ["Juror", "Jurymitglied"],
  [
    "Justiziar",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Kamerad", "Wegbegleitung; solidarisch wegbegleitende Person; Teammitglied"],
  ["Kameramann", "Kameraperson; Kamera"],
  ["Kameramänner", "Kamerateam; Kamera; Kamerapersonen"],
  ["Kämmerer", "Leitung der Kämmerei"],
  ["Kampfrichter", "Kampfjury; Schiedsgericht"],
  ["Kampfrichterverzerrung", "Verzerrung durch Kampfrichtende/n"],
  ["Kandidaten", "Kandidierende"],
  ["Kandidatenfragen", "Personalfrage; K-Frage"],
  ["Kandidatenvorschlag", "Personalvorschlag"],
  ["Kanzler", "Regierung (an-)führende Person; Regierungsoberhaupt"],
  ["Kanzleramt", "Amt des Regierungsoberhauptes"],
  ["Kapitäne", "Schiffsführende"],
  ["Karnevalisten", "Karneval Feiernde"],
  [
    "Karteninhaber",
    "die Karte besitzende Person; Karteninhabende Person; weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Kassenwart", "Kassenverwaltung; Finanzverwaltung; Vermögensverwaltung"],
  ["Kassierer", "Person an der Kasse"],
  ["Katholiken", "Menschen katholischen Glaubens"],
  ["Käufer", "Kaufende; Kundschaft"],
  ["Kaufmann", "Kauffachkraft; Kaufkraft"],
  ["Kaufmänner", "Kaufleute"],
  [
    "kaufmännisch",
    "zahlentechnisch; finanztechnisch; in Zahlen gesehen; kauftechnisch; in Zahlen gesehen; buchungstechnisch; fiskalisch; (markt-)wirtschaftlich; ökonomisch; geschäftlich; gewerblich; kommerziell",
  ],
  ["keiner", "niemand"],
  ["Kellner", "Servicekraft; Bedienung"],
  [
    "Keramiker",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Kinderarztpraxis", "Praxis für Kinderheilkunde"],
  ["Kindergärtner", "pädagogische Fachkraft; Erziehungskraft; Kita-Fachkraft"],
  ["Kindermädchen", "Kinderbetreuung; Aupair"],
  ["Kindertagepfleger", "Kindertagespflegeperson"],
  ["Kläger", "klagende Person"],
  ["Klassensprecher", "Klassenvertretung"],
  ["Kleinbauern", "kleine Landwirtschaftsbetriebe"],
  ["Kletterer", "Kletternde"],
  [
    "Klient",
    "ratsuchende Person; Beratung in Anspruch nehmende Person; Person, die in die Beratung kommt; Fall; Besuch",
  ],
  ["Klienten", "Klientel"],
  ["klientenorientiert", "orientiert am Bedarf der ratsuchenden Person"],
  ["Koch", "Lebensmittel verarbeitende Person; in der Küche arbeitende Person"],
  ["Kollege", "mitarbeitende Person; Teammitglied"],
  ["Kollegen", "Kollegschaft; Kollegium; Teammitglieder"],
  ["Kolonialherr", "Kolonialmacht; Suzerän"],
  ["Kolonialherren", "Kolonialmächte"],
  ["Kommentator", "kommentierender Pressemensch; kommentierende Presse"],
  ["Kommentatoren", "Kommentar von Medienschaffenden"],
  ["Kommilitone", "mitstudierende Person"],
  ["Kommilitonen", "Mitstudierende"],
  ["Kommissionierer", "Mitarbeitende in der Warenzusammenstellung"],
  ["Kommunikator", "kommunizierende Person"],
  ["Komparse", "stumme Rolle; Person ohne Sprechrolle; Nebenfigur"],
  ["Kompetenzträger", "Kompetenz tragende Person"],
  ["Kompetenzträger", "Kompetenztragende"],
  ["Komponist", "musikschaffende Person; kompositionstätige Person"],
  ["Komponisten", "Musikschaffende; Kompositionstätige"],
  ["Konfirmand", "zu konfirmierende Person; Konfi"],
  ["Konfirmanden", "zu Konformierende; Konfis"],
  ["Konfirmanden", "Jugendliche in der Konfirmationsvorbereitung"],
  ["Konfirmandenunterricht", "Konfirmationsunterricht"],
  ["Königsdisziplin", "anspruchvollste Disziplin; Spitzendisziplin"],
  [
    "Konsortialpartner",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Kontrahent", "Gegenüber"],
  ["Kontoinhaber", "kontoinhabende Person; kontoführende Person"],
  ["Konkurrent", "Konkurrenz"],
  [
    "Konsumenten",
    "Konsumierende; Kundschaft; einkaufende / konsumierende Zielgruppe",
  ],
  ["Kooperationspartner", "in Kooperation mit; Kooperationsbeteiligte"],
  ["Koordinator", "Koordination"],
  ["Kraftfahrer", "fahrzeugführende Person"],
  ["Kraftfahrer", "Kraftfahrzeugführende"],
  ["Krankenpfleger", "Pflegefachkraft; Pflegekraft; Pflegefachperson"],
  [
    "Krankenpfleger",
    "Pflegekräfte; Pflegefachpersonen; Pflegepersonal; Beschäftigte in der Krankenpflege; professionell Pflegende; Pflegende",
  ],
  ["Krankenschwester", "Pflegefachkraft; Pflegekraft; Pflegefachperson"],
  [
    "Krankenschwestern",
    "Pflegekräfte; Pflegepersonal; Beschäftigte in der Krankenpflege; professionell Pflegende; Pflegende",
  ],
  ["Kreditnehmer", "kreditnehmende Person"],
  ["Kreditnehmer", "Kreditnehmende"],
  [
    "Kreisbeigeordneter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Kriegerkodex",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Kriminalbeamter", "Person im Beamtenverhältnis bei der Kriminalpolizei"],
  ["Kritiker", "Kritisierende; Kritische; kritische Stimmen"],
  ["Küchenhelfer", "Küchenhilfe"],
  [
    "Kunde",
    "Kundschaft; Klientel; kaufende Person; Mensch; Person; weitere Alternativen gesucht, v.a. im Zusammenhang mit Dienstleistungen im Internet: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Kunden",
    "Kundschaft; Klientel; kaufende Personen; Menschen; Personen; Nutzende; Auftraggebende; Nachfrage",
  ],
  ["Kundenauftrag", "Auftrag durch Kundschaft; Auftrag"],
  ["Kundenbedürfnisse", "Bedürfnisse der Kundschaft"],
  ["Kundenberatung", "Beratung der Kundschaft"],
  ["Kundenbewertungen", "Bewertungen; Bewertungssterne; Sterne-Bewertungen"],
  ["Kundendienst", "Service; Support"],
  [
    "kundenfreundlich",
    "praktisch zu bedienen; publikumsfreundlich; nutzungsfreundlich",
  ],
  [
    "Kundengruppe",
    "Kundschaft [mit bestimmtem Merkmal, z.B. Kundschaft mit geringer Kaufkraft]",
  ],
  ["Kundenkonto", "Nutzungskonto"],
  ["Kundenprojekt", "Kundschaftsprojekt"],
  ["Kundenreferenz", "Referenz"],
  ["Kundenstamm", "treue Kundschaft; feste Kundschaft; Kundschaftsstamm"],
  ["kundenorientiert", "publikumsorientiert"],
  ["Kundenwerbung", "Akquise"],
  ["Kundenwünsche", "Wünsche der Kundschaft"],
  ["Kundenzentrum", "Servicezentrum"],
  ["Kundenzufriedenheit", "Zufriedenheit der Kundschaft"],
  ["Kunstfreunde", "Kunstbegeisterte"],
  ["Kunstkenner", "Kunstkennende"],
  ["Künstler", "Act"],
  ["Künstler", "Kunstschaffende"],
  ["Künstlername", "(künstlerisches) Pseudonym; Kunstname"],
  ["Kunstsammler", "Kunstsammelnde"],
  ["Kuratoren", "Kuratierende; kuratorische Leitung"],
  ["Kursadministrator", "Perosn, die den Kurs leitet; Kursadmin"],
  ["Kursteilnehmer", "am Kurs teilnehmende Person"],
  ["Kursteilnehmer", "Kursteilnehmende; am Kurs Teilnehmende"],
  ["Kurzarbeitergeld", "Kurzarbeitsgeld"],
  ["Laborant", "Laborfachkraft"],
  ["Laborarbeiter", "Laborfachkraft"],
  [
    "Laie",
    "Mensch ohne Fachkenntnisse; fachunkundige Person; fachfremde Person",
  ],
  ["Laien", "Fachunkundige; Fachfremde; Nichtkundige"],
  [
    "Landrat",
    "Landkreisleitung; Kreisverwaltungsleitung; Landratsamtsleitung; Dienststellenleitung; Amtsvorstand",
  ],
  ["Landsmänner", "Landsleute"],
  ["Landwirt", "Landwirtschaft betreibende Person"],
  [
    "Landwirte",
    "Landwirtschaft Betreibende; landwirtschaftlich Beschäftigte; Beschäftigte in der Landwirtschaft",
  ],
  ["Läufer", "laufsporttreibende Person"],
  ["Lehrer", "Lehrperson; Lehrkraft"],
  [
    "Lehrer",
    "Lehrkräfte; Lehrpersonen; das Kollegium; Lehrende; Unterrichtende",
  ],
  ["Lehrerberuf", "Lehrberuf"],
  [
    "Lehrerkonferenz",
    "Kollegiumskonferenz; Konferenz; Konferenz der Lehrkräfte; Besprechung der Lehrkräfte",
  ],
  ["Lehrerpult", "Tisch/Pult der Lehrkraft; Schreibtisch"],
  ["Lehrerzimmer", "Arbeitszimmer der Lehrkräfte; Teamraum"],
  [
    "Lehrling",
    "Nachwuchskraft; Person in Ausbildung; auszubildende Person; lernende Person",
  ],
  ["Lehrlinge", "Auszubildende; Lernende"],
  ["Lehrstuhlinhaber", "Leitung des Lehrstuhles"],
  ["Lehrstuhlinhaber", "Leitende eines Lehrstuhles"],
  ["Lehrstuhlleiter", "Leitung des Lehrstuhls"],
  ["Lehrstuhlleiter", "Leitende eines Lehrstuhles"],
  [
    "Leibeigener",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Leistungsbezieher", "Leistung Beziehende"],
  ["Leistungsträger", "refinanzierende Ämter und Behörden"],
  ["Leiter", "Leitung"],
  ["Lektor", "das Lektorat"],
  ["Lektorstelle", "Lektoratsstelle"],
  ["Lenker", "Fahrzeug lenkende Person"],
  ["Lernbegleiter", "lernbegleitende Person"],
  ["Lernender", "lernende Person"],
  ["Leser", "lesende Person"],
  ["Leser", "Lesepublikum; Leserschaft; lesende Zielgruppe; Lesende"],
  ["Leserausweis", "Leseausweis; Bibliotheksausweis"],
  ["Leserbrief", "Zuschrift / Kommentar zum Artikel xy"],
  ["Leserbriefe", "Ihre Kommentare/Meinungen; offene Zuschriften"],
  ["leserfreundlich", "lesefreundlich"],
  [
    "Lesermarkt",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Lieber", "An ...; Hallo ...; Guten Tag ..."],
  ["Liebhaber", "Begeisterte"],
  ["Liedermacher", "Liederschaffende; Lieder kreierende Personen"],
  ["Lieferant", "Lieferfirma; lieferndes Unternehmen; Lieferunternehmen"],
  ["Linkshänder", "linkshändige Person"],
  ["Literaturkritiker", "Literatur kritisierende Person"],
  ["Literaturkritiker", "Literaturkritisierende"],
  ["Lobbyist", "Interessen vertretende Person"],
  ["Macher", "Aktive"],
  ["Mädchenname", "Geburtsname"],
  ["Magier", "Zauberkunst ausübende Person"],
  ["Makler", "Häuser vertreibende Personen"],
  ["Maklerverbund", "Maklerei"],
  ["Maler", "Werkschaffende der Malerei"],
  ["man", "Sie; viele; wir; ich"],
  ["Manager", "Management; Unternehmensführung; Führungskraft"],
  ["Mandant", "Mandantschaft"],
  ["Manipulant", "manipulierende Person"],
  ["Mann", "Person(en) ..."],
  ["Ein-Mann-Betrieb", "... Eine-Person-Betrieb"],
  ["Zwei-Mann-Zelt", "... Zwei-Personen-Zelt; Zweier-Zelt"],
  ["Männchen", "Figürchen; Spielfigur"],
  [
    "Manndeckung",
    "1:1-Verteidigung; 1:1-Deckung; personenorientierte Deckung; Direktdeckung [Gegensatz zur Raumdeckung]",
  ],
  [
    "mannlos",
    "personenlos; computergesteuert; autonom; unbesetzt; selbstständig",
  ],
  ["Manntage", "Arbeitstage; Leistungstage; Personentage"],
  ["Mannsbild", "gestandene Person, Powermensch"],
  ["Mannschaft", "Team; Gruppe; Kollektiv; Besatzung [bei Schiffen]"],
  ["Damenmannschaft", "... Damenteam"],
  ["Frauenmannschaft", "... Frauenteam"],
  ["Mädchenmannschaft", "... Mädchenteam"],
  ["Mannstunde", "Personenstunde"],
  ["Manpower", "Arbeitskraft"],
  [
    "Marktschreier",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Mathematiker",
    "mathematisch qualifizierte Person; sich mit Mathematik befassende Person",
  ],
  ["Matrose", "Mitglied der Schiffsbesatzung (mit unterstem Dienstrang) "],
  [
    "Mechaniker",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "KfZ-Mechaniker-Innung",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Mechatroniker", "Fachkraft für Mechatronik"],
  ["Mediator", "Mediation; Mediationsperson; Mediation anbietende Person"],
  ["Medienanbieter", "Medienorganisationen"],
  ["Mediengestalter", "Mediengestaltende"],
  ["Medienpartner", "in Medienpartnerschaft mit ..."],
  ["Mediziner", "medizinisches/ärztliches Fachpersonal"],
  ["Mehrbenutzerfunktion", "Funktion für mehrere Nutzende"],
  ["Meinungsführer", "meinungsführende Person"],
  ["Meister", "Person mit höherer Fachprüfung"],
  [
    "Meister",
    "Erster Platz der Deutschen Meisterschaft / Weltmeisterschaft; Erstplatzierte (pl.)",
  ],
  ["Meisterschaft", "Turnier; Wettbewerb"],
  ["Mensch", "[ist bereits genderneutral; analog zur PERSON]"],
  [
    "Mentee",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Mentor",
    "Vorbild; fürsprechende Person; beratende Person; fördernde Person; Begleitung; Kontaktperson; Ansprechperson; Ausbildungsbeauftragte Person",
  ],
  ["Mieter", "Mietperson; Mietpartei"],
  ["Mieterverein", "Mietverein; Mietvertretung"],
  [
    "Migrant",
    "Person mit Migrationshintergrund; eingewanderte Person; der/die Migrierte",
  ],
  [
    "Migranten",
    "Personen mit Migrationshintergrund; Eingewanderte; Zugewanderte; Migrierte",
  ],
  [
    "Milchmädchenrechnung",
    "Trugschluss; Irrtum; falsche Erwartung; Fehlschluss; Illusion",
  ],
  [
    "Minderjähriger",
    "Kind unter 18; minderjährige Person weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Minderjährige", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Mindestteilnehmerzahl", "Mindestanzahl Teilnehmende"],
  ["Minister", "Ressortleitung"],
  ["Minister", "Ressortleitende"],
  ["Ministerpräsidenten", "MPs; Landesoberhaupt; Vorsitz der Resortleitenden"],
  ["Mitarbeiter", "Arbeitskraft; Teammitglied"],
  [
    "Mitarbeiter",
    "Mitarbeitende; Beschäftigte; Angestellte; Tätige; Belegschaft; Teammitglieder; Arbeitskräfte; Kollegium; Personal; Teammitglieder; Werktätige; Betriebs-/Konzern-/Firmen-/Unternehmensangehörige; bei uns beschäftigte Personen; Festangestellte; Arbeitsgemeinschaft; Arbeitsgruppe; Beteiligte; Crew; Gruppe; Servicekräfte; Servicepersonal; Team",
  ],
  ["Mitarbeiterbeurteilung", "Personalbeurteilung; Angestelltenbeurteilung"],
  ["Mitarbeiterführung", "Personalmanagement; Personführung; Personalpolitik"],
  [
    "Mitarbeitergespräch",
    "Dienstbesprechung; Qualifikationsgespräch; Arbeitsgespräch; Beurteilungsgespräch; Jahresgespräch; Beschäftigtengespräch; Personalgespräch; Mitarbeitendengespräch",
  ],
  [
    "Mitarbeiterorientierung",
    "orientiert an den Mitarbeitenden; Mitarbeitendenorientierung",
  ],
  ["Mitarbeitersuche", "Personalsuche; Mitarbeitendensuche"],
  ["Mitarbeiterstellen", "Stellen für Mitarbeitende; Arbeitsplätze"],
  ["Mitarbeiterverpflegung", "Personalverpflegung"],
  ["Mitbewerber", "die Konkurrenz"],
  ["Mitbewohner", "Wohnungsteilende"],
  ["Mitbürger", "Mitmensch"],
  ["Mitbürger", "Landsleute; Mitmenschen; Staatsangehörige"],
  ["Mitfahrergelegenheit", "Mitfahrgelegenheit"],
  [
    "Mitglied",
    "[als Neutrum ist dieses Wort schon gendergerecht: DAS Mitglied]",
  ],
  [
    "Mitglieder",
    "[als Neutrum ist dieses Wort schon gendergerecht: DAS Mitglied (sg.) - die Mitglieder (pl.); wer dennoch eine Alternative bevorzugt, kann diese hier nutzen:] Zugehörige; Angehörige; Teil von ...",
  ],
  [
    "Mitläufer",
    "Folge leistende Person; involvierte Person; passives Engagement; passive Rolle",
  ],
  ["Mitschüler", "andere Kinder aus der Klasse / Schule; Mitlernende"],
  ["Mitspieler", "Mitspielende"],
  ["Mitstreiter", "Mitwirkende; Teilnehmende; Gleichgesinnte"],
  ["Mittelsmann", "Mittelsperson; Mittelsmensch"],
  [
    "Mittelständler",
    "mittelständische Unternehmen; Angehörige des Mittelstandes",
  ],
  ["Mitwisser", "Eingeweihte"],
  ["Moderator", "Moderation; moderierende Person"],
  ["Modeschöpfer", "Mode Schaffende"],
  ["Mofafahrer", "Mofa Fahrende"],
  ["Monteur", "montierende Person"],
  ["Mörder", "einen Mord begehende Person; mordende Person"],
  [
    "Müllmann",
    "Müll entsorgende Person; Fachkraft für Kreislauf- und Abfallwirtschaft",
  ],
  ["Müllmänner", "Beschäftigte der Müllabfuhr; Müllabfuhr"],
  [
    "Multiplikator",
    "Person, die Informationen/Wissen weitergibt; Wissen/Informationen weitergebende Person",
  ],
  ["Münchner", "die Münchner Bevölkerung"],
  ["Musiker", "Act"],
  [
    "Musiker",
    "Musikausübende; Musikschaffende; Musikspielende; Musizierende; Mitglieder eines Orchesters; Bandmitglieder",
  ],
  ["Muslim", "Mensch muslimischen Glaubens"],
  ["Musterknabe", "Vorbild; Musterschulkind"],
  ["Mutter", "Elternteil"],
  ["Mutter-Kind-Gruppe", "... Eltern-Kind-Gruppe"],
  ["Mütterberatung", "Elternberatung"],
  ["mütterlicherseits", "[vornamen-]licherseits "],
  ["Muttermal", "Pigmentstörung; Leberfleck"],
  ["Muttermilch", "Elternmilch; Brustmilch"],
  ["Mutterschutz", "Elternschutz "],
  [
    "Muttersprache",
    "Erstsprache; erste Sprache; Elternsprache; Familiensprache; Heimatsprache",
  ],
  [
    "Muttersprachler",
    "Person mit der Erstsprache XYZ; Person, die XYZ als Erstsprache spricht; xyz-erstsprachliche Person (z.B. polnisch-erstsprachliche Person)",
  ],
  ["Nachahmer", "Menschen; andere; Menschen gleicher Gesinnung"],
  ["Nachbarn", "nebenan Wohnende"],
  ["Nachbarn", "Hausgemeinschaft"],
  ["Nachbarschaft", "Umgebung"],
  ["Nachfahren", "Nachkommenschaft"],
  ["Nachfolger", "Nachfolge"],
  ["Nachfrager", "Nachfragende"],
  ["Nachrücker", "nachrückende Person(en)"],
  ["Nachtschwärmer", "Nachtmensch; Partymensch"],
  ["Nachtschwärmer", "Nachtleute"],
  ["Nachwuchswissenschaftler", "wissenschaftlicher Nachwuchs"],
  ["Näherinnen", "Nähende"],
  ["Namensvetter", "Gleichnamige"],
  [
    "Narr",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Narren", "Närrische"],
  ["Nationalmannschaft", "Nationalteam"],
  ["Naturbursche", "Naturmensch"],
  ["Nebenmann", "nebenstehende Person"],
  ["Netzwerkpartner", "Netzwerkbeteiligte; Netzwerkmitglieder"],
  [
    "Neueinsteiger",
    "Nachwuchs; neu im Geschäft; unerfahrene Person; Grünschnabel; Mensch ohne Vorkenntnisse",
  ],
  ["Nichtraucher", "nicht rauchende Person"],
  ["Notar", "notariell arbeitende Person"],
  ["Nutzer", "(be-)nutzende Person; Person, die ... nutzt"],
  ["Nutzer", "Personen, die ... nutzen; Nutzung; Mitglieder; Nutzende"],
  ["Nutzerentgelte", "Nutzungsentgelte"],
  ["Nutzergemeinde", "Community; Netzwerk"],
  [
    "Nutzergruppe",
    "mit (folgenden) Aufgaben betrauter/arbeitender Personenkreis; Nutzungsgruppe",
  ],
  ["Nutzerhandbuch", "Handbuch; Nutzungshandbuch"],
  ["Nutzerkonto", "Account; Konto; Zugang"],
  [
    "nutzerorientiert",
    "menschzentriert; nutzungsfreundlich; nutzungsorientiert",
  ],
  [
    "Oberarzt",
    "ärztliche Führungskraft; weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Obmann", "Obmensch; schiedsrichtende Person"],
  ["Ökonom", "ökonomisch ausgebildete Person"],
  ["Ombudsmann", "Ombudsperson"],
  ["Opfer", "[als Neutrum ist dieses Wort schon gendergerecht: DAS Opfer]"],
  [
    "Opportunisten",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Organisatoren",
    "Organisation; Organisationsteam/-komitee; organisiert von ...; Organisierende",
  ],
  ["Organspender", "Organ Spendende; Organ spendende Personen"],
  ["Pächter", "pachtende Person"],
  ["Pädagoge", "pädagogische Fachkraft"],
  ["Paketbote", "Paketzustellung"],
  ["Parlamentarier", "Abgeordnete"],
  ["Partner", "Gegenüber"],
  [
    "Partner",
    "Unterstützung; Mitglied; Beteiligte; Kooperationen; Mitwirkende",
  ],
  ["Partnerarbeit", "Zweierarbeit; Paararbeit; Tandemarbeit"],
  ["Partnerländer", "Kooperationsländer"],
  ["Partnerorganisation", "(mit uns) kooperierende Institution"],
  ["Partnerschaft", "Beziehung; Kooperation; Zusammenarbeit; Tandem"],
  [
    "Partnersuche",
    "Lebensmenschsuche; Verbündetensuche; Seelenverwandtensuche",
  ],
  ["Passagier", "reisende Person"],
  ["Passagiere", "Reisende"],
  [
    "Passanten",
    "Passierende; Vorübergehende  ; einen Ort passierende Personen; den Gehweg nutzende Personen; weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Passantenbefragung", "Straßenbefragung"],
  ["Passinhaber", "im Besitz eines Passes"],
  ["Pate", "Patenamt; Patenschaft"],
  [
    "Pathologe",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Patient",
    "zu behandelnde Person; kranke Person; zu versorgende Person; (Fach-)Beratung aufsuchende Person; Person, die sich in medizinische Hände begibt; Hilfesuchende Person; stationär aufgenommene Person weitere Alternativen gesucht, v.a. für den Gebrauch innerhalb der Dokumentation: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Patienten",
    "zu behandelnde Personen; Personen, die in (ärztlicher) Behandlung sind; Kranke; Erkrankte; Menschen mit einer Erkrankung; Menschen, die im Krankenhaus liegen; (von einer Krankheit) Betroffene; Behandelte; Hilfesuchende",
  ],
  ["Krebspatienten", "... von der Krebskrankheit Betroffene"],
  [
    "Patienten-Arzt-Kommunikation",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Privatpatient",
    "Privatversicherte Person; Person mit privater Krankenversicherung",
  ],
  [
    "Patientencharakteristik",
    "Betroffenencharakteristik; Erkranktencharakteristik",
  ],
  [
    "Patienteninformation",
    "Information; Information für Sie weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Patientenkontakt", "Betroffenenkontakt"],
  ["patientennah", "Point-of-Care"],
  [
    "patientenorientiert",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Patientenschulung", "Schulung für Erkrankte"],
  [
    "Patientenstamm",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Patientenverfügung", "Verfügung(en) für betreuende Personen"],
  ["Patientenversorgung", "ärztliche Versorgung; Behandlung; Pflege"],
  [
    "Patientenzimmer",
    "Krankenzimmer (nicht empfohlen) ; Gesundungszimmer; Heilungszimmer; Zimmer",
  ],
  [
    "Pazifist",
    "Person, die für Frieden kämpft; friedensengagierte Person; pazifistische Person weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Pazifisten", "Friedensbewegte"],
  ["Pendler", "Pendelnde"],
  [
    "Pendlerpauschale",
    "Entfernungspauschale; Pendelpauschale; Pauschale für Pendelnde; Pauschale für Menschen, die pendeln",
  ],
  ["Performer", "Performende"],
  ["Person", "[ist bereits genderneutral; analog zur MENSCH]"],
  ["Personalentwickler", "Personalentwicklung"],
  ["Personalleiter", "Personalleitung"],
  ["Personalrat", "Mitglied des Personalrates"],
  [
    "Personalräte",
    "Mitglieder des Personalrates; der Personalrat; Mitarbeitendenvertretung",
  ],
  ["Personalvertreter", "Personalvertretung"],
  [
    "Pfadfinder",
    "Scout; Pfadi weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Pfadfinder", "Pfadis; Pfadfindende"],
  ["Pfarrer", "Pfarrperson"],
  ["Pfleger", "Pflegekraft"],
  ["Pfleger", "Pflegekräfte; Pflegepersonal; die Pflege; Pflegende"],
  ["Pförtner", "Pfortenpersonal"],
  ["Philosoph", "gelehrte Person"],
  ["Philosophen", "Gelehrte"],
  ["Physiker", "Person mit abgeschlossenem Physikstudium"],
  ["Physiotherapeut", "Physiotherapie praktizierende Person"],
  ["Pilot", "flugzeugführende Belegschaft"],
  ["Pilotlabor", "Koordinationslabor; Koordinierungslabor"],
  ["Pilotphase", "Testphase; Probebetrieb"],
  ["Pilotprojekt", "Versuchsvorhaben; Versuchsprojekt; Testphase"],
  ["Pionier", "vorkämpfende Person"],
  ["Pionierarbeit", "wegbereitende Arbeit; bahnbrechende Leistung"],
  ["Planer", "planende Personen; planende Institutionen"],
  ["Poet", "lyrikschaffende Person"],
  [
    "Politiker",
    "Menschen in der Politik; Menschen, die in der Politik tätig sind; Mitglieder der Politik",
  ],
  ["Polizist", "Polizeikraft; Polizei"],
  ["Polizisten", "Polizei; Polizeikräfte; Polizeileute"],
  [
    "Polsterer",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Postbote", "Postzustellung"],
  [
    "Praktikant",
    "Praktikumskraft ; eine ein Praktikum absolvierende Person; eine Person im Praktikum; eine sich in einem Praktikum(verhältnis) befindende Person",
  ],
  ["Praktikanten", "Auszubildende im Praktikum"],
  ["Praktikantenstelle", "Praktikumsstelle"],
  [
    "Praktiker",
    "Praktizierende; Leute aus der Praxis; praktisch veranlagte Menschen",
  ],
  ["Präsident", "Staatsoberhaupt; Vorsitz"],
  ["Präsidenten", "Vorsitzende"],
  ["Präsidentenwahl", "Präsidentschaftswahl"],
  ["Prediger", "Predigende"],
  ["Preisträger", "ausgezeichnete Person"],
  ["Pressesprecher", "Pressevertretung; Öffentlichkeitsarbeit; Pressestelle"],
  ["Proband", "Testperson; Versuchsperson"],
  ["Probanden", "Testpersonen; Versuchspersonen; Teilnehmende"],
  ["Produzent", "die Produktionsleitung innehabende Person"],
  ["Produzenten", "Produzierende; Produktionsteam"],
  ["Professor", "eine Professur innehabende Person; Prof."],
  ["Professoren", "Professorenschaft"],
  ["Professorenstelle", "Professorale Stelle"],
  ["Profi", "Fachperson; Person mit Fachwissen/Fachkenntnis"],
  ["Profis", "Sachkundige; Fachleute; Sachverständige"],
  ["Programmierer", "programmierende Person"],
  ["Programmierer", "Softwareerstellende; Programmierende"],
  ["Projektentwickler", "Projektentwicklung"],
  ["Projektleiter", "Projektleitung"],
  ["Projektleiter", "Projektleitungen; Projektleitende"],
  [
    "Projektpartner",
    "Projektbeteiligte; am Projekt beteiligte Firmen/Institute/etc.",
  ],
  ["Projektträger", "Projektträgerschaft"],
  [
    "Proletarier",
    "Lohnabhängige; Werktätige; Arbeitende; Angehörige des Proletariats",
  ],
  ["Prominenter", "prominente Persönlichkeit"],
  [
    "Protagonist",
    "Figur; Hauptperson; Hauptfigur; zentrale Gestalt; Schlüsselfigur; Titelrolle",
  ],
  [
    "Protagonisten",
    "Hauptpersonen; Hauptfiguren; zentrale Gestalten; Schlüsselfiguren; Titelrollen; Aktive",
  ],
  ["Protokollführer", "protokollführende Person"],
  [
    "Prüfer",
    "Prüfungsleitung; Prüfungsabnahme durch ...; geprüft von ... ; Person, die prüft; prüfende Person",
  ],
  ["Prüfling", "zu prüfende Person"],
  ["Prüfstatiker", "Statik prüfende Person"],
  ["Psychologe", "psychologische Fachkräfte"],
  [
    "Psychotherapeut",
    "psychotherapeutisches Fachpersonal; psychotherapeutische Fachkraft",
  ],
  ["Putzfrau", "Reinigungspersonal; Reinigungskraft; Raumpflege"],
  ["Querdenker", "Querkopf; kreativer Kopf"],
  ["Rabbiner", "Mitglied des Rabbinats"],
  ["Rabbiner", "Rabbinat"],
  ["Radfahrer", "Rad Fahrende; wer mit dem Rad unterwegs ist ..."],
  [
    "Radiologe",
    "radiologisch-ärztliches Fachpersonal weitere Alternativen gesucht; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Rassist", "rassistische Person"],
  ["Ratgeber", "Wegbegleitung; Beistand; ratgebende/beratende Person"],
  ["Ratsherr", "Mitglied des Stadtrats "],
  ["Raucherabteil", "Abteil für Rauchende; Abteil zum Rauchen"],
  [
    "Raucherbereich",
    "Bereich für Rauchende; Bereich zum Rauchen; Rauchbereich",
  ],
  ["Raucherpause", "Zigarettenpause"],
  ["Rechnungsempfänger", "die Rechnung empfangende Person"],
  ["Rechnungsempfänger", "Rechnungsempfangende; Rechnungserhaltende"],
  [
    "Rechnungsprüfer",
    "Rechnungsprüfung; Person, die die Rechnungsprüfung macht; Person, die für die Rechnungsprüfung verantwortlich ist",
  ],
  [
    "Rechtsanwalt",
    "Rechtsbeistand (nicht empfohlen) , Mitglied der (Rechts-)Anwaltschaft; Rechtsvertretung",
  ],
  ["Rechtsanwälte", "Angehörige rechtsberatender Berufe"],
  ["Rechtshänder", "rechtshändige Person"],
  ["Redakteur", "Redaktion; Redationsmitglied"],
  ["Redner", "referierende Person; vortragende Person"],
  ["Rednerliste", "Redeliste"],
  ["Rednerpult", "Redepult"],
  ["Referendar", "Lehrkraft im Referendariat"],
  [
    "Referent",
    "referierende Person; vortragende Person; weitere Alternativen gesucht, insbesondere für den Referent als Stellenbezeichnung, z.B. Wissenschaftlicher Referent in der Stiftung XYZ; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Referenten", "Referierende; Vortragende"],
  ["Regierungschef", "Staatsoberhaupt; Regierung anführende Person"],
  ["Regisseur", "Regie"],
  ["Rehasportler", "Rehasportinteressierte"],
  ["Reiseleiter", "Reiseleitung"],
  ["Rekrut", "Nachwuchs (der Grundausbildung in der Bundeswehr)"],
  ["Rektor", "Schulleitung"],
  ["Rentner", "Person im Ruhestand; Person in Rente"],
  [
    "Rentner",
    "Menschen, im Rentenalter; Menschen, die in der Rente sind; Menschen in Rente",
  ],
  [
    "Repetent",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Reporter", "Presse; berichterstattende Person; Medienvertretung"],
  ["Repräsentanten", "Vertretung"],
  [
    "Respondent",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Rettungsassistent", "Rettungsassistenz"],
  [
    "Rettungssanitäter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Rettungsschwimmer", "aus dem Wasser rettende Person"],
  ["Rettungshelfer", "Rettungshilfe; rettungshilfeleistende Person"],
  ["Rezeptionist", "Empfang; Person/Perosonal am Empfang; Rezeption"],
  ["Rezipient", "rezipierende Person; empfangende Person"],
  ["Rezipienten", "Rezipierende; Publikum"],
  ["Richter", "rechtsprechende Person"],
  ["Richter", "Richterschaft"],
  [
    "Ritter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Ritterschlag",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Ritterstand",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Rollstuhlfahrer", "Person im Rollstuhl"],
  ["Ruderer", "rudernde Person"],
  ["Sachbearbeiter", "Verwaltungskraft"],
  ["Sachbearbeiter", "Verwaltungskräfte; Sachbearbeitende; Sachverständige"],
  [
    "Sachbearbeiternummer",
    "Kennnummer; Verwaltungsnummer; Nummer der zuständigen Verwaltungskraft",
  ],
  ["Sachverständiger", "Person mit Sachverstand in ..."],
  [
    "Salafist",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Sammler", "Sammelnde"],
  ["Sänger", "Stimme; Act"],
  [
    "Sänger",
    "Stimmen; Chor; Choraktive; Personen, die singen; Gesangsgruppe; Singende",
  ],
  ["Sanitäter", "Rettungskräfte; Sanitätsdienst"],
  ["Schatzmeister", "Finanzvorstand; Kassenführung; Kassenverwaltung"],
  ["Schauspieler", "Rollen; Besetzung; Darstellende"],
  [
    "Schiedsrichter",
    "Spielleitung; schiedsrichtende Person; schiedsrichtendes Gremium; Schiedsgericht",
  ],
  ["Schirmherr", "Support; gefördert/unterstützt von..."],
  [
    "Schirmherrschaft",
    "Support; gefördert/unterstützt von...; Vorstand; Repräsentanz",
  ],
  ["Schlägertyp", "gewalttätige Person"],
  ["Schlichter", "Schlichtende; Schlichtungspersonen"],
  ["Schmied", "auf die Schmiedekunst spezialisierte Person"],
  ["Schneemann", "Schneefigur"],
  ["Schöpfer", "(er-)schaffende Person"],
  ["Schöpfer", "(Er-)Schaffende"],
  ["Schreiber", "schreibende Person"],
  ["Schriftsteller", "bücherschreibende Person"],
  [
    "Schriftsteller",
    "Urheberrechtsinhabende; Verfassende; Schreibende; Literaturschaffende",
  ],
  ["Schulabbrecher", "Geringqualifizierte; Menschen ohne Schulabschluss"],
  ["Schuldiger", "schuldige Person"],
  ["Schuldige", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Schuldner", "die in Schuld stehende Person"],
  ["Schüler", "Schulkind; Klassenmitglied; lernende Person"],
  [
    "Schüler",
    "Schulkinder; Kinder; Jugendliche; die Klasse; Lernende; Beschulte; Klassenmitglieder; Mädchen und Jungen; Schülerschaft",
  ],
  ["Schüleraustausch", "Schulaustausch"],
  ["Schülerausweis", "Schulausweis"],
  ["Schülerbegegnung", "Schulbegegnung; Klassenbegegnung"],
  [
    "Schülerexperiment",
    "Gruppenexperiment; Klassenexperiment; Einzelexperiment",
  ],
  [
    "Schülerfahrtkosten",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Schülerlabor", "Schullabor"],
  ["Schülerpraktikum", "Schulpraktikum; Praktikum in der Schulzeit"],
  [
    "Schülervertreter",
    "Person, die die Schülerschaft vertritt; Lernendenvertretung",
  ],
  [
    "Schülervertreter",
    "Schulkindervertretung; Vertretung der Lernenden weitere Alternativen gesucht; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Schülervorstellungen",
    "Schulaufführungen; weitere Alternativen gesucht, insbesondere für Vorstellungen von Projektarbeiten; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Schülerzeitung",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick) ; [Schulzeitung: nicht zu empfehlen] ",
  ],
  ["Schulleiter", "Schulleitung"],
  ["Schulsozialarbeiter", "Fachkraft für Schulsozialarbeit"],
  ["Schulträger", "Schulträgerschaft"],
  ["Schütze", "schießende Person; Schuss abgebende Person/Dienstkraft"],
  ["Schützenkönig", "treffsicherste Person"],
  ["Schwimmer", "schwimmende Person; Mensch mit Spaß am Schwimmen"],
  ["Schwimmlehrer", "Schwimmlehrkraft"],
  ["Seefahrer", "Seeleute"],
  ["Seemann", "Hochsee-Fachkraft; maritime Fachkraft"],
  ["seinerzeit", "zu jener Zeit; damals; einst; früher"],
  ["seinesgleichen", "von gleicher Art"],
  [
    "Seiteneinsteiger",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Sekretärin", "Verwaltungskraft; Assistenz; Schreibkraft; Bürokraft"],
  [
    "Sekretärinnen",
    "Verwaltungskräfte; Verwaltungsfachangestellte; Assistenzen; Schreibkräfte; Bürokräfte",
  ],
  ["Selbstabholer", "bei Selbstabholung"],
  ["Selbstmörder", "einen Selbstmord/Suizid begehende Person"],
  ["Selbstständiger", "selbstständig arbeitende Person"],
  ["Seminarleiter", "Seminarleitung"],
  ["Sender", "gesendet von ..."],
  ["Sender-Empfänger-Problem", "Sende-Empfang-Problem"],
  ["Sender-Nachricht-Empfänger-Modell", "Kommunikationsmodell"],
  ["Sender", "Sendende"],
  [
    "Senioren",
    "ältere Menschen; Menschen im Rentenalter; Menschen im 3. Lebensalter",
  ],
  [
    "Seniorenbeirat",
    "Älterenbeirat; Ruhestandsbeirat; Beirat für das 3. Lebensalter",
  ],
  [
    "Seniorenangebot",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Sexist", "sexistische Person"],
  [
    "Sheriff",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Showmaster", "Showleitung; Showmoderation; moderierende Person"],
  [
    "Sicherheitsbeauftragter",
    "für Sicherheit zuständige/beauftragte Person; für Sicherheitsthemen zuständige/beauftragte Person",
  ],
  ["Siedler", "Ansässige; Siedelnde"],
  ["Sieger", "Erster Platz; erstplatzierte Person"],
  [
    "Siegerehrung",
    "Bestenehrung; Bestenauszeichnung; Ehrung der gewinnenden Personen",
  ],
  ["Sitznachbar", "Person neben mir; nebenan sitzende Person"],
  [
    "Sklave",
    "versklavte Person; in Sklaverei gehaltene Person; unfreier Mensch; leibeigene Person",
  ],
  ["Sklaven", "Versklavte; in Sklaverei Gehaltene; Unfreie; Leibeigene"],
  ["Sklavenhalter", "Sklaverei Ausführende"],
  ["Soldat", "Mitglied der Streitkräfte eines Landes "],
  ["Soldaten", "Streitkräfte "],
  ["Sozialarbeiter", "Fachkraft für Soziale Arbeit"],
  ["Sozialarbeiter", "Sozialarbeitende; Fachkräfte der Sozialen Arbeit"],
  ["Sozialpädagoge", "sozialpädagogische Fachkraft"],
  [
    "Sozialversicherungsfachangestellter",
    "in der Sozialversicherung fachangestellte Person",
  ],
  ["Späher", "ausspähende Person"],
  [
    "Spaziergänger",
    "Person zu Fuß; spazierende Person; wandernde Person; Wandersperson",
  ],
  ["Spaziergänger", "Personen zu Fuß"],
  ["Spediteur", "für den Warentransport beauftragte Person"],
  ["Spekulant", "spekulierende Person"],
  ["Spender", "Gebende; Sponsoring; Spenden"],
  ["Spezialisten", "Sachkundige; Fachleute; Sachverständige"],
  ["Spezialistenfunktion", "Sachkundigenfunktion"],
  ["Spieler", "Teammitglied"],
  ["Spieler", "Spielende; Teammitglieder"],
  [
    "Spielverderber",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Spion", "auskundschaftende Person; spionierende Person"],
  [
    "Sprecher",
    "Stimme; Text gesprochen von; Moderation; Kommentar; Ansage; sprechende Person",
  ],
  ["Sprecher", "Sprachrohr; Pressestelle; Öffentlichkeitsarbeit"],
  ["Sprecher", "Sprechende; Sprachbenutzende"],
  ["Sprecher", "Abgeordnete"],
  ["Springer/Springerdienst", "Ersatz; Vertretung; Stellvertretung"],
  ["Sponsoren", "Sponsoring; geldgebende Personen/Firmen"],
  ["Sportfreunde", "Mitglieder des/unseres Vereins"],
  ["Sportler", "sporttreibende Person"],
  ["Sportler", "Sporttreibende"],
  ["Staatsbürgerschaft", "Staatsangehörigkeit; Nationalität"],
  [
    "Staatsmänner",
    "Volksbeauftragte; Menschen in der Politik; Mitglieder des Bundestags / Bundesrats / der Regierung / ...; MdB",
  ],
  [
    "Stadtführer",
    "Stadtführung; Reiseleitung; [ist das Buch / der Prospekt gemeint, muss nicht gegendert werden]",
  ],
  ["Stakeholder", "Anspruchsgruppe"],
  ["Star", "berühmte Persönlichkeit; Berühmtheit"],
  ["Steinewerfer", "Steinewerfende; Steine werfende Personen"],
  ["Stelleninhaber", "Stelle ausführende Person; Funktion begleitende Person"],
  ["Stellvertreter", "Stellvertretung"],
  [
    "Steuerberater",
    "Steuerberatung; Steuerkanzlei; zu Steuern beratende Person; der steuerberatenden Berufe angehörige Person",
  ],
  ["Steuerberater", "Angehörige der steuerberatenden Berufe"],
  ["Steuerberaterpraxis", "Steuerberatungspraxis"],
  ["Steuerhinterzieher", "Steuerhinterziehende"],
  ["Steuerschuldner", "steuerschuldige Person"],
  ["Steuerzahler", "steuerzahlende Person; steuerpflichtige Person"],
  [
    "stiefmütterlich",
    "stiefelterlich; achtlos; nachlässig; gleichgültig; lieblos",
  ],
  ["Stifterrat", "Stiftungsrat"],
  ["Stifterversammlung", "Stiftungsversammlung"],
  ["Stipendiat", "geförderte Person"],
  ["Stipendiaten", "Studierende mit Stipendium; Geförderte"],
  ["Störer", "Störende"],
  ["Strafgefangener", "Person in Haft"],
  ["Sträfling", "Person in Haft"],
  ["Straftäter", "straffällige Person"],
  ["Strahlemann", "Sonnenschein"],
  ["Strichmännchen", "Strichfigürchen; Strichmensch; Strichmenschlein"],
  ["Student", "Studi; Mitglied der Studierenden"],
  ["Studenten", "Studierende; Studies"],
  ["Studentenjob", "Studierendenjob; Studijob; Job"],
  ["Studentenwerk", "Studierendenwerk"],
  ["Studentenwohnheim", "Studierendenwohnheim"],
  ["Studienanfänger", 'Studienbeginnende; "Erstis"; Erstsemestrige'],
  ["Studienbewerber", "Studienbewerbungen; Einschreibungen"],
  [
    "Supervisor",
    "Person mit Führungsverantwortung; Person mit leitender Funktion/mit\nKontrollfunktionen; weitere Alternativen gesucht, insbesondere für psychologisch ausgebildete Person, die Supervision anbietet; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Supervisoren", "Supervidierende"],
  ["Supporter", "Mitwirkende; Befürwortende"],
  [
    "Tagesmutter",
    "Tagespflege(person); Tagesbetreuung; Kinderbetreuung; Tageselter ",
  ],
  ["Tagesmütter", "Tageseltern"],
  ["Talkmaster", "Moderation; moderierende Person"],
  ["Tante-Emma-Laden", "Minimarkt; Laden für Waren des täglichen Bedarfs"],
  ["Tänzer", "Tanzende; Tanzbegeisterte"],
  ["Tatbeteiligter", "an einer Tat beteiligte Person"],
  ["Tatbeteiligte", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Täter", "Unrechtsperson"],
  [
    "Täter",
    "Unrechtspersonen; Tatbegehende ; Kriminelle; (Straf-)Tat begangen von...",
  ],
  ["Täterrolle", "Tatbegehende"],
  ["Taucher", "Tauchsport ausübende Person; tauchende Person"],
  [
    "Täufling",
    "Taufkind; getauft werdende Person; zu taufende Person weitere Alternativen gesucht, insbesondere für den erwachsenen Täufling; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Teamleiter", "Teamleitung"],
  ["Techniker", "technische Fachkraft"],
  [
    "Technologe",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Teilnehmer", "mitwirkende Person; teilnehmende Person"],
  [
    "Teilnehmer",
    "Teilnehmende; Beteiligte; alle, die an ... teilnehmen; Anwesende; Anmeldungen",
  ],
  ["Teilnehmergebühr", "Teilnahmegebühr; Kursgebühr; Kosten"],
  ["Teilnehmerliste", "Teilnahmeliste; Anwesenheitsliste; Teilnehmendenliste"],
  [
    "teilnehmerorientiert",
    "subjektorientiert; personorientiert; teilnehmendenorientiert; gruppenorientiert",
  ],
  ["Teilnehmerzahl", "Teilnahmezahl; Gruppengröße; Anmeldezahl"],
  [
    "Telemitarbeiter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Telemitarbeiter", "Telemitarbeitende"],
  [
    "Terrorist",
    "des Terrors verdächtigte Person; eines Terroranschlags überführte Person",
  ],
  ["Terroristen", "Terrorisierende"],
  ["Tester", "Testende; Testpersonen"],
  ["Testleiter", "Testleitung"],
  ["Theaterpädagoge", "theaterpädagogische Fachkraft"],
  ["Theoretiker", "theoretisch Arbeitende"],
  ["Therapeut", "therapeutisches Fachpersonal"],
  ["Therapeuten", "Therapierende"],
  ["Tierarzt", "tiermedizinisches Fachpersonal"],
  ["Tierhalter", "tierhaltende Person"],
  ["Tierschützer", "im Tierschutz engagierte Perosn"],
  ["Tierschützer", "Tierschützende"],
  [
    "Töpfer",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Tote", "Getötete; zu Tode/ums Leben Gekommene"],
  [
    "Tourguide",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Touristen", "Urlaubsgäste "],
  ["Träger", "Trägerschaft; verantwortliche Einrichtung/Körperschaft"],
  ["Trainer", "Übungsleitung; moderierende Person"],
  [
    "Trainer",
    "Moderierende; Referierende; Vortragende; Unterrichtende; Lehrende",
  ],
  ["Trauzeuge", "die Trauung bezeugende Personen; Trauungsbegleitung"],
  ["Trauzeugen", "die Trauung Bezeugende; Trauungsbegleitung"],
  ["Treuhänder", "treuhändisch beauftragte Person"],
  ["Tüftler", "tüftelnde Person"],
  ["Tutor", "studentische Hilfskraft; Übungsgruppenleitung; Tutoriumsleitung"],
  [
    "Tutoren",
    "Übungs(an)leitende; Tutoriumsbegleitende; Ratgebende; Begleitung; studentische Hilfskräfte",
  ],
  [
    "Überbringer",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["übermannen", "überkommen; überwältigen"],
  ["Übersetzer", "Übersetzende; Literatur Übersetzende"],
  [
    "Übungsleiter",
    "sportliche/technische/praktische Anleitung; anleitende Person",
  ],
  [
    "Umschüler",
    "Umlernende; Umschulende; die zu Qualifizierenden; Personen in beruflicher Neuorientierung",
  ],
  ["Unbekannter", "unbekannte Person"],
  [
    "unbemannt",
    "ohne Besatzung; maschinengesteuert; autonom; ferngesteuert; unbesetzt; robotisch; personenlos",
  ],
  ["Unternehmer", "Gewerbe betreibende Person; selbstständige Person"],
  [
    "Unternehmer",
    "Selbstständige; Wirtschaftstreibende; Geschäftsleute; Gewerbe Betreibende",
  ],
  [
    "Unterstützer",
    "support; Förderung durch ...; unterstützendes Unternehmen; unterstützende Person",
  ],
  [
    "Unterstützer",
    "support; Geldgebende; Förderung durch ...; Mitwirkende; Befürwortende",
  ],
  ["Unterzeichner", "unterzeichnende Person; unterzeichnende Partei"],
  ["Unterzeichner", "Unterzeichnende"],
  ["Urheber", "Person der Urheberschaft"],
  [
    "Urheberrecht",
    "Recht auf Urheberschaft; [nicht zu empfehlen: Copyright ; Recht auf geistiges Eigentum ]",
  ],
  ["Urlauber", "reisende Person; urlaubende Person"],
  ["Urlauber", "Reisende"],
  ["User", "Nutzende; Personen, die Apps/Software nutzen; Mitglieder"],
  ["V-Mann", "V-Person"],
  ["V-Männer", "V-Leute"],
  ["Vater", "Elternteil"],
  ["Vaterland", "Heimatland; Geburtsland; Erstland"],
  ["väterlicherseits", "[vornamen-]licherseits "],
  ["Veganer", "vegan lebende Person"],
  ["Vegetarier", "vegetarisch lebende Person"],
  ["Veranstalter", "veranstaltet durch/von ... ; Organisation; Ausrichtung"],
  [
    "Veranstalter",
    "Einladende; veranstaltet durch/von ... ; Organisation; Ausrichtung",
  ],
  [
    "Verantwortlicher",
    "die Verantwortung tragende Person; verantwortliche Person",
  ],
  ["Verantwortliche", "[im Plural ist dieses Wort schon gendergerecht]"],
  ["Verbandsgesellschafter", "Vertretungen / Beteiligte der Verbände"],
  ["Verbandsvertreter", "Vertretungen / Beteiligte der Verbände"],
  [
    "Verbraucher",
    "Kundschaft; Konsumierende; Privatpersonen weitere Alternativen gesucht, z.B. zu Verbraucher im Sinne des BGB; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Verbraucherschutz",
    "Konsumierendenschutz weitere Alternativen gesucht; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Verbraucherschützer", "für den Verbraucherschutz beauftragte Person"],
  ["Verbrecher", "Person, die eine Straftat/ein Verbrechen begeht"],
  ["Verbrüderung", "Verschwisterung"],
  [
    "Verbündeter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Verfasser", "verfasst von; Autorenschaft"],
  [
    "Verfechter",
    "für einen Standpunkt einstehende Person; für ... einstehende Person",
  ],
  ["Verfolgungsakteure", "Verfolgende"],
  ["Vergewaltiger", "eine Vergewaltigung begehende Person"],
  [
    "Verhandlungspartner",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Verkäufer", "Kaufhauspersonal; Personal"],
  [
    "Verkäufer",
    "Kaufhauspersonal; Personal; Verkaufskräfte; Anbietende; Handeltreibende",
  ],
  ["Verkehrssünder", "Verkehrsregeln missachtende/verstoßende Person"],
  ["Verkehrsteilnehmer", "Verkehrsbeteiligte"],
  ["Verleger", "Publizierende"],
  ["Verleiher", "verleihende Person"],
  ["Verletzter", "verletzte Person"],
  ["Verlierer", "der letzte Platz"],
  ["Verlierer", "die Letzten"],
  [
    "Verlobter",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Vermieter", "vermietende Person"],
  ["Vermittler", "Mittelsperson"],
  [
    "Versichertenkarte",
    "Versicherungskarte; Gesundheitskarte; Krankenkassenkarte",
  ],
  ["Versichertennummer", "Versicherungsnummer"],
  [
    "Versicherungsnehmer",
    "versicherte Person , Versichung abschließende Person",
  ],
  [
    "Versicherungsnehmer",
    "versicherte Personen; Versicherte  , Versicherung abschließende Personen",
  ],
  ["Verstorbener", "verstorbene Person"],
  ["Versuchsleiter", "Versuchsleitung"],
  ["Verteidiger", "Verteidigung; Rechtsvertretung"],
  ["Vertragspartner", "Vertragspartei"],
  ["Vertragspartner", "Vertragsparteien"],
  ["Vertreter", "in vertretender Position; Mitglied von ..."],
  [
    "Vertreter",
    "vertreten durch; Vertretung; Delegierte; Abgesandte; Abgeordnete; Beauftragte; Mitglieder; Vertretende",
  ],
  ["Verursacher", "verursachende Person"],
  ["Verursacher", "Verursachende"],
  ["Verwalter", "verwaltende Person/Firma/Institution; Verwaltung"],
  ["Verwandter", "Familienmitglied"],
  ["Verwender", "verwendende Person"],
  ["Verwender", "Verwendende"],
  ["Veteran", "altgediente Person"],
  ["Veteranen", "Altgediente; ehemalige Kriegsteilnehmende"],
  [
    "Virologen",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Vizepräsident",
    "Vizevorsitz; weitere Alternativen gesucht: senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Volontärsbeauftragter", "beauftragte Person fürs Volontariat"],
  ["Vordenker", "vordenkende Person; Weg bereitende Person"],
  ["Vordermann", "Person davor; Person, die davor kam"],
  ["Vorgänger", "vorangegangene Person; Person vor mir"],
  ["Vorgängerprojekt", "Vorprojekt; vorangegangenes Projekt"],
  ["Vorgängerstudie", "Vorstudie; vorangegangene Studie"],
  ["Vorgesetzter", "Führungskraft"],
  ["Vormund", "die Vormundschaft innehabende Person; Vormundschaft"],
  ["Vorläufer", "älteres/altes Modell"],
  [
    "Vorreiter",
    "Person an der Spitze; Person, die etwas vorlebt; Person, die voraus denkt/handelt",
  ],
  ["Vorreiterrolle", "Führungsrolle"],
  ["Vorsitzender", "den 1. Vorsitz hat ..."],
  ["Vorstand", "Vorstandsmitglied; im Vorstand"],
  ["Wachmann", "Wachpersonal"],
  ["Wächter", "Wache"],
  [
    "Wähler",
    "Wahlberechtigte; alle, die zur Wahl gegangen sind; Stimmberechtigte",
  ],
  ["Wählerinitiative", "Initiative der Wahlberechtigten"],
  ["Wählerverzeichnis", "Wählendenverzeichnis; Wahlverzeichnis"],
  ["Wahlmänner", "Wahlleute"],
  ["Waidmannsheil!", "Waidleutsheil!"],
  ["Wanderer", "wandernde Person; Person auf Wanderung"],
  ["Wart", "überwachende Person"],
  ["Wegbegleiter", "wegbegleitende Person; Wegbegleitung"],
  ["Wegbereiter", "Weg bereitende Person; prägende Person"],
  ["Wegewart", "Wege überwachende Person"],
  ["Weggefährte", "Wegbegleitung"],
  ["weltmännisch", "cosmopolitisch; weltgewandt"],
  ["Weltmarktführer", "Weltmarktführende"],
  [
    "Werkstudent",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  ["Werkstudenten", "Werkstudierende"],
  ["Werkstudentenstelle", "Werkstudierendenstelle"],
  ["Werkzeugmechaniker", "Fachkraft für Werkzeugmechanik"],
  ["Wettbewerber", "Konkurrenz; Wettbewerbsteilnehmende"],
  ["Widersacher", "Widerpart; Konkurrenz"],
  ["Winzer", "Weinbau betreibende Person"],
  ["Wirtschaftsprüfer", "Angehörige der wirtschaftsprüfenden Berufe"],
  ["Wirtschaftswissenschaftler", "Forschende der Wirtschaft(swissenschaft)"],
  ["Wissenschaftler", "Mensch aus der Wissenschaft"],
  [
    "Wissenschaftler",
    "Forschende; wissenschaftliches Personal der Universität; Menschen aus der Wissenschaft; wissenschaftliche Arbeitskraft",
  ],
  ["Wissensträger", "Wissenstragende Person; des Wissens mächtige Person"],
  ["Witwer", "Verwitwete"],
  ["Workshopleiter", "Workshopleitung"],
  ["Xylophonspieler", "Xylophon Spielende"],
  [
    "YouTuber",
    "noch kein passender Begriff gefunden; senden Sie Ihren Vorschlag über das Kontaktformular (klick)",
  ],
  [
    "Zahnarzt",
    "zahnärztliches Fachpersonal; Fachkraft der Zahnmedizin; zahnmedizinisches Fachpersonal",
  ],
  [
    "Zahnarztpraxis",
    "Praxis für Zahnerhaltung; zahnmedizinische Praxis; Praxis für Zahnmedizin",
  ],
  ["Zauberer", "Zaubertrick vorführende Person"],
  ["Zauberer", "Zauberkunstschaffende"],
  ["Zehnkämpfer", "am Zehnkampf teilnehmende Person"],
  ["Zeitgenosse", "Mitmensch"],
  ["Zeuge", "bezeugende Person"],
  ["Zeugen", "Bezeugende"],
  ["Zimmerer", "Zimmereifachkraft"],
  ["Zimmermädchen", "Servicekraft; Raumpflege; Reinigungskraft"],
  ["Zimmermann", "Zimmereifachkraft"],
  ["Zivilist", "Zivilperson"],
  ["Zivilisten", "Zivilpersonen"],
  ["Zoobesucher", "Zoogäste ; Zoobesuche"],
  ["Züchter", "Fachperson Tier-/Pflanzen-/...-Zucht"],
  ["Zuhörer", "Publikum; Auditorium; Zuhörerschaft"],
  ["Zulieferer", "Zulieferfirma"],
  ["Zuschauer", "Person aus dem Publikum"],
  ["Zuschauer", "Publikum; Zuschauende"],
  ["Zuständiger", "zuständige Person"],
  [
    "Zuwanderer",
    "Zugewanderte; Personen mit Migrationshintergrund; Eingewanderte; Migrierte",
  ],
];
